### ISSUE TITLE
medleydb_melody melody3 type not in mir_eval format

### ISSUE THREAD

**Issue by rabitt** [mir-dataset-loaders/mirdata#101]
`mir_eval` expects a ragged array for multipitch outputs, but `melody3` data in `mirdata` is a numpy array.

**Comment by magdalenafuentes** [comment]
`sections` are given now as a `SectionData` object, with `start_times`, `end_times`, and `sections` attributes. `mir_eval` expects an array of intervals (which means concatenate `start_times` and `end_times`) and an array with sections. 

Should we modify the `SectionData` object accordingly? Also: when playing around with that found 
 issues in the annotations such as intervals of length 0 or timestamps bigger than track duration :/ thoughts?

**Comment by rabitt** [comment]
@magdalenafuentes can you open a separate issue about the sections?
