### ISSUE TITLE
guitarset.download doesn't create the right folder structure

### ISSUE THREAD

**Issue by rabitt** [mir-dataset-loaders/mirdata#113]
everything is unzipped directly to `~/mir_datasets/GuitarSet` instead of into the specific subfolders. This is partially because `download_utils.downloader` by default downloads directly into `data_home`. We should add an option to `RemoteFileMetadata` which optionally specifies a subfolder to create and unzip data into.

**Comment by tomxi** [comment]
I've got a fix coming.... I'm just cleaning up the git branches to make the PR look prettier, but essentially it's #114.
