### ISSUE TITLE
beatles.download checksum error

### ISSUE THREAD

**Issue by rabitt** [mir-dataset-loaders/mirdata#116]
When I run `mirdata.beatles.download()`, everything appears to download as expected, but the checksums don't match. Can someone else run the same and see if you can reproduce it? The checksum of my downloaded file is `c3b7d505e033ea9ff0d7a1d57871f2ee`, vs the expected `62425c552d37c6bb655a78e4603828cc`

**Comment by rabitt** [comment]
I'm getting the same, repeatable, error for Salami:

```
/Users/rachelbittner/mir_datasets/Salami/salami-data-public-master.zip has an MD5 checksum (f88b3455f1f2443458d094f603c0c1c7) differing from expected (b01d6eb5b71cca1f3163fae4b2cd4c61), file may be corrupted.
```

**Comment by magdalenafuentes** [comment]
You're right, I can reproduce both errors in linux and windows, will fix them now
