### ISSUE TITLE
when downloading, set the cleanup=True as default?

### ISSUE THREAD

**Issue by rabitt** [mir-dataset-loaders/mirdata#117]
By default, in all the downloaders we set `cleanup=False`, so any downloaded zip or tar files are left there in the folder. This is nice for the `force_overwrite` parameter, which only checks for the existence of the zip/tar files, but annoying for the user since the resulting folders are messier and it will take up more space. Maybe we can rethink how we handle `force_overwrite`. Any thoughts/ideas?

**Comment by keunwoochoi** [comment]
I think we should def remove the original files. I'd prob even up for removing `force_overwrite` if we can't think of any other nice way to implement it. ..and it seems pretty tricky because we wouldn't like to checksum *all* the files I assume.

**Comment by rabitt** [comment]
100% agree Keunwoo. 

One consideration is if e.g. the download takes a lot of time with multiple files and fails somewhere in the middle. The way it is now, you rerun and it picks up from where it left off. If we delete stuff as it's successfully downloaded, rerunning download will again download the zip/tar files and uncompress them. I don't have a good idea for a way around this.

**Comment by rabitt** [comment]
Just discussed this with @magdalenafuentes offline - in order to handle datasets with multiple zip files that might take a long time to download, we decided to keep the default to `False`.
