### ISSUE TITLE
mirdata doesn't work cleanly for datasets not on disk

### ISSUE THREAD

**Issue by rabitt** [mir-dataset-loaders/mirdata#128]
For the use case where the data files live on a remote machine and are accessed when needed for e.g. for training a model, many of mirdata's assumptions fail:
* validation expects files to be local
* annotation loaders look for files locally
* annotation loading functions are hidden from the user
* `Track` annotation attributes are loaded in the background from disk, expecting files to be present

How can we support this (relatively common) use case cleanly? This will be increasingly important for larger datasets. Some initial ideas:
* expose annotation loading functions to the user
* create functions for validating a single file within a dataset
* better handle errors when accessing `Track` attributes that load files from disk

cc @faroit

**Comment by faroit** [comment]
hi there. I didn't really look into mirdata yet but I consider adding MUSDB18.... are does multichannel audio work in mirdata?

> How can we support this (relatively common) use case cleanly?

can you elaborate on this use case a bit more and give some examples? are you talking about applications where the data is is in key/value databases?

> expose annotation loading functions to the user

Yes, I would do both, the audio loader and the annotation loader.

**Comment by rabitt** [comment]
Me and @magdalenafuentes discussed this a bit more, and here are some things we think would help make this usable for remote datasets:

1) Add `load_audio` functions for each loader
2) Expose annotation and audio paths as attributes in Track objects
3) Expose all load_* functions, and add documentation for which annotation paths they are built to load
4) Add an example in the documentation of loading local vs. remote data
