### ISSUE TITLE
Download progress bar doesn't work

### ISSUE THREAD

**Issue by rabitt** [mir-dataset-loaders/mirdata#133]
We changed something, and the progress bar when running `dataset.download` doesn't work :(

**Comment by drubinstein** [comment]
All datasets or just one in particular?

**Comment by rabitt** [comment]
all datasets

**Comment by drubinstein** [comment]
Can you try pinning the tqdm version? Looks like they updated it a couple of weeks ago and since it is unpinned you just grabbed the most recent version. Could be that that version is causing problems.
