### ISSUE TITLE
Checksums for .tar files are different between urllib and requests

### ISSUE THREAD

**Issue by magdalenafuentes** [mir-dataset-loaders/mirdata#136]
This happens at least in `Beatles` and `Salami`, any other dataset?

**Comment by rabitt** [comment]
Not sure...we should (ugh..) just run all the downloaders and see...

**Comment by rabitt** [comment]
I went through each of the downloaders:
* beatles ❌(62425c552d37c6bb655a78e4603828cc)
* guitarset ✅ 
* ikala ✅
* medley_solos_db ✅
* meldeydb_melody ✅
* medleydb_pitch ✅
* orchset ✅
* rwc_classical ✅
* rwc_genre ✅
* rwc_jazz ✅
* rwc_popular ✅
* salami ✅

It seems like salami is now working?
