### ISSUE TITLE
pronounciation vs pronunciation

### ISSUE THREAD

**Issue by keunwoochoi** [mir-dataset-loaders/mirdata#142]
https://www.quora.com/What-are-the-differences-between-pronounciation-and-pronunciation

So, there's no such word as 'pronounciation' but a common typo of 'pronunciation'... and our attribute names of iKala.

Should we fix this?

**Comment by rabitt** [comment]
Yep, let's fix!

**Comment by rabitt** [comment]
Closed in #143
