### ISSUE TITLE
Salami audio tests break

### ISSUE THREAD

**Issue by magdalenafuentes** [mir-dataset-loaders/mirdata#146]
Getting a backend error when using  `audioread` to read `salami` audiio files. Now those lines in `test_salami` are commented but should be fixed

**Comment by drubinstein** [comment]
1. How do I reproduce
2. Which lines in the test are you referring to?

**Comment by drubinstein** [comment]
If you're referring to the lines 66-68 in `test_salami.py` I uncommented and they worked for me. This may be happening because you are using librosa >= 0.7.0. which `Replaced the default audio decoder with pysoundfile, and only use audioread as backup.`. If you're on linux you need `libsndfile1` to use that version of librosa.

**Comment by rabitt** [comment]
@drubinstein yes lines 66-68 in test_salami.py. they work locally but @magdalenafuentes was telling me that they fail on the remote build. I think it's again some missing dependency.

**Comment by drubinstein** [comment]
@rabitt based on https://circleci.com/gh/mir-dataset-loaders/mirdata/1537?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link it looks like the mp3 file is invalid

```
err = 21
prefix = "Error opening 'tests/resources/mir_datasets/Salami/audio/2.mp3': "

    def _error_check(err, prefix=""):
        """Pretty-print a numerical error code if there is an error."""
        if err != 0:
            err_str = _snd.sf_error_number(err)
>           raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
E           RuntimeError: Error opening 'tests/resources/mir_datasets/Salami/audio/2.mp3': File contains data in an unknown format.
```

**Comment by drubinstein** [comment]
Doing further research and after finding https://github.com/librosa/librosa/issues/945 it looks like ffmpeg needed to be added into the linux test images.
