### ISSUE TITLE
Project description on pypi is lacking

### ISSUE THREAD

**Issue by alastair** [mir-dataset-loaders/mirdata#151]
If I view this library on pypi I get a very basic description that doesn't tell me much about the project

> Common loaders for MIR datasets

It'd be nice to extend this with either the readme from the repository, or a different detailed description

**Comment by lostanlen** [comment]
Relatedly, there is no definition of the MIR acronym anywhere in the mirdata package. It might be good to state somewhere (README + PyPI description) that MIR means music information retrieval.

**Comment by lostanlen** [comment]
closed by #171
