### ISSUE TITLE
Canonical datasets

### ISSUE THREAD

**Issue by rabitt** [mir-dataset-loaders/mirdata#156]
When we generate the index file for a dataset, we're running it on a 'canonical' version of the dataset, which lives on the pull requester's computer. Should we store this version of the dataset somewhere stable (e.g. zenodo, with closed access) for traceability?

This opens a bit of a can of worms - we don't want to host/distribute datasets...

**Comment by lostanlen** [comment]
I've taken a brief look at Zenodo's Terms of Use, and this looks OK. I am not a lawyer, but it seems like Zenodo file hosting under closed access could be seen as a backup copy, and therefore fall under the private use clause.
