### ISSUE TITLE
Are we missing the audio attribute in __repr__ in loaders?

### ISSUE THREAD

**Issue by magdalenafuentes** [mir-dataset-loaders/mirdata#160]
or is it on purpose?

**Comment by lostanlen** [comment]
What would this audio representation show? Duration, number of channels, and sample rate?

**Comment by lostanlen** [comment]
Looking at this again, we must be reminded of the fact that some MIR datasets do not have audio. Some have only features, some have MIDI, some have song popularity, etc. Does mirdata plan to cover those?
(see fourth column of http://ismir.net/resources/datasets/)

But for the audio case, i'm OK with writing a routine for pretty-printing a `__repr__` for audio that encompasses duration, number of channels, and sample rate.

**Comment by rabitt** [comment]
I think we should rethink how `__repr__` behaves in general. Right now for some loaders it's just printing partial information about the Track attributes, and for others it's more complete. This is also one of the functions that's quite cumbersome to write and test. I'd like to look into a way we can auto-generate this and populate it by inheriting from a base class.

**Comment by rabitt** [comment]
Discussed offline with @magdalenafuentes and @lostanlen  - we will implement a base class that Track objects inheret from which will automatically implement `__repr__` so that every loader is consistent.
