### ISSUE TITLE
jams_converter ignores note_data

### ISSUE THREAD

**Issue by lostanlen** [mir-dataset-loaders/mirdata#161]
The `jams_utils` module has no `notes_to_jams`, which causes the `jams_converter` kwarg `note_data` to be ignored.

https://github.com/mir-dataset-loaders/mirdata/blob/master/mirdata/jams_utils.py#L33

**Comment by magdalenafuentes** [comment]
You're right! Good catch

**Comment by magdalenafuentes** [comment]
The only `note` namespaces in `jams` are under the `pitch` namespace, and is either `note_hz` or `note_midi`, no musical notes (see docs [here](https://jams.readthedocs.io/en/stable/namespace.html#pitch)). Thoughts @rabitt @lostanlen ?

**Comment by rabitt** [comment]
@magdalenafuentes how is musical notes different from e.g. note_midi?

**Comment by magdalenafuentes** [comment]
After discussing with @rabitt and @lostanlen will convert `NoteData` type into `note_midi` using `librosa`
