### ISSUE TITLE
Auto-generated test template

### ISSUE THREAD

**Issue by magdalenafuentes** [mir-dataset-loaders/mirdata#162]
It would be great to have something like this to save time in writing new loaders and also reviewing PRs

**Comment by lostanlen** [comment]
@magdalenafuentes i'm not sure how this would look like? at any rate, i would prefer to unify the modules and write a cross-module unit test.

**Comment by rabitt** [comment]
That's a great point Vincent - there are some functions which are common to every module that we could test in bulk by default. In particular, `validate`, `load`, `download`, `track_ids` and `cite` should exist for every dataset. This would leave the user to test only their (necessarily custom) `Track` object, which is work.
