### ISSUE TITLE
"mirdata failed to download the dataset" does not print the offending URL

### ISSUE THREAD

**Issue by lostanlen** [mir-dataset-loaders/mirdata#168]
The error message in "mirdata failed to download the dataset" should not have an exclamation mark (let's not shout at the user!!!) and i think that it would be more informative if it printed the broken URL. Am i right?

**Comment by magdalenafuentes** [comment]
could be addressed in #122

**Comment by rabitt** [comment]
^^ update - let's keep this open, but make sure it's addressed by #179

**Comment by rabitt** [comment]
Closed by #216
