### ISSUE TITLE
Check if dataset is available locally

### ISSUE THREAD

**Issue by rabitt** [mir-dataset-loaders/mirdata#17]
If a dataset is "available" on disk, we should know it. There are three possible states for a given dataset:
1) exists and valid (the `.validate()` function returns empty dictionaries)
2) exists and not valid (at least one file in the dataset index exists, but some may be missing or have invalid checksums)
3) does not exist (no files in the dataset exist locally)

Let's indicate states (1) and (2) by files called `_VALIDATED` and `_INVALID.json` which live in the dataset folder, e.g. `Orchset/_VALIDATED`.

1) when calling `.download()`, first check if `_VALIDATED` exists. If it does not (or if `clobber=True`) download the dataset / print instructions to download. Otherwise, print something that indicates that the dataset already exists and is valid.
2) In `utils.validator()` if `_VALIDATED` exists, don't run validation. Add a flag to the function to force run even if `_VALIDATED` exists.
3) At the end of `utils.validator()`, create an empty `_VALIDATED` file is run successfully without missing/invalid files. If every file in the index is missing, print something that tells the user the dataset is not available locally. If some files are missing/some are invalid, create `_INVALID.json` which saves the dictionaries of invalid/missing files.

**Comment by drubinstein** [comment]
Why have validated files? Wouldn't it be easier to assume that if it exists, it is valid? If it is ever invalid we delete the directory and tell the user?

**Comment by magdalenafuentes** [comment]
When validating checksums, what happens if the local dataset is in a compressed format, e.g. flac, mp3?

**Comment by rabitt** [comment]
@drubinstein 

> Why have validated files? 

There are a few reasons, the main one being speed. For the upcoming issues #21 and #22 , they'll require having this information. It could be computed when those functions are run, but validating that the checksums are equal is slow to be run each time, especially as the datasets get bigger. 

> Wouldn't it be easier to assume that if it exists, it is valid?

Hard no on this one. One of the driving points for this library is reproducibility/consistency of datasets. It's unfortunately often the case that people will have different versions of the data. We introduced the checksums to make sure, file by file, that a local version of a dataset is consistent with an "official" one.

> If it is ever invalid we delete the directory and tell the user?

If the data were easily available I'd say yes, but very often the data can be precious and hard to get again, so I don't want to be deleting user's files.

**Comment by rabitt** [comment]
@magdalenafuentes 

> When validating checksums, what happens if the local dataset is in a compressed format, e.g. flac, mp3?

I think it all should be fine. As far as I understand, md5 checksums just look at sequences of bites, and hash them. mp3 or other formats are still just sequences of bites, should be fine :)

**Comment by rabitt** [comment]
@magdalenafuentes do you mean if the local audio files are in a different file format than the originals, e.g. original is wav, local is mp3?

**Comment by magdalenafuentes** [comment]
Yes, exactly. Are we going to check that? If so, we could convert them? Or suggest the user to do it?

**Comment by rabitt** [comment]
mmm... is it really common? I'd lean towards just throwing the regular validation error saying the file we expect is missing, and the user will hopefully adjust their dataset.

**Comment by magdalenafuentes** [comment]
OK, just thought it could be informative if we check the extension. I think is ok if we already say somewhere that we're checking that the audio file is **exactly** the same including quality, extension, length.

**Comment by drubinstein** [comment]
I feel like (2) should not be done. If we redownloaded and untarred the dataset, we should always rerun validation since you are now changing the bytes on the computer.

**Comment by rabitt** [comment]
Agree, but what if we still have (2), but always force rerun validation from scratch when we run the download function?

**Comment by drubinstein** [comment]
Agreed.

Also where do you want the files stored? I can't seem to figure out a good path.

**Comment by rabitt** [comment]
How about in `data_home/DATASET_NAME`?

**Comment by drubinstein** [comment]
That works!

**Comment by rabitt** [comment]
Fixed in #43
