### ISSUE TITLE
mirdata has no logo

### ISSUE THREAD

**Issue by lostanlen** [mir-dataset-loaders/mirdata#172]
here's the logo of the `mir-dataset-loaders` organization as of today:
![48734618](https://user-images.githubusercontent.com/3943142/75099072-6619bf80-558b-11ea-8a0b-38be2e256103.png)

The fact that this is a default GitHub avatar, and not a custom visual, is potentially detracting users for adopting mirdata as a package. It would be good if we could remedy that.

I'm by no means a graphic designer, but i came up with this visual, just to get the conversation started:
![mirdata_logo](https://user-images.githubusercontent.com/3943142/75102068-2535a100-55b3-11ea-826f-94e47534c2ca.png)

**Comment by keunwoochoi** [comment]
I think we could try to unbias the treble clef centric perspective, a probably completely wrong social norm.

**Comment by lostanlen** [comment]
@keunwoochoi that's a very good point. so what do we do?

**Comment by rabitt** [comment]
![image](https://user-images.githubusercontent.com/8169843/75115964-c5caa600-5631-11ea-9f1a-922c1b311ff1.png)

**Comment by lostanlen** [comment]
![mirdata_logo_v3](https://user-images.githubusercontent.com/3943142/75116172-9fa60580-5633-11ea-9a3d-faf20fa5ba95.png)

**Comment by lostanlen** [comment]
@magdalenafuentes thoughts?

**Comment by magdalenafuentes** [comment]
It does now! After offline discussion with @lostanlen and @rabitt we merged ideas into:

![Asset 2](https://user-images.githubusercontent.com/24395454/76050754-9ae82800-5f36-11ea-992d-ccb4736c62ef.png)

**Comment by lostanlen** [comment]
nice job @magdalenafuentes ! i will announce on twitter
