### ISSUE TITLE
Refactor `dataset.download`

### ISSUE THREAD

**Issue by rabitt** [mir-dataset-loaders/mirdata#179]
* define a global downloads variable which is a dictionary mapping from download type to a dictionary of key value pairs of identifier: download object
* Allow partial download of objects by specifying a list of key - by default download everything (possibly simplify the whole `download` function and `download_utils.downloader` function)
* Add a mandatory print statement controlled by an argument `verbose=True` which is printed before downloading before downloading begins with information about what is happening.

**Comment by lostanlen** [comment]
Yes, that would be fantastic to have as a feature. In this way, we'd have a hierarchy:
dataset module > dataset object > dataset sample

module implements a Track class, a cite function, and a dictionary of objects (as @rabitt defines it)
object can be downloaded, loaded (as index), and validated
sample can be loaded (as audio) and is interoperable with JAMS and mir_eval 


> Add a mandatory print statement controlled by an argument verbose=True which is printed before downloading before downloading begins with information about what is happening.

This is a bit orthogonal in my opinion, but worth keeping in the scope of this issue. I don't know if this is possible, but it would be great if we could estimate the size of each download object, the current Internet bandwidth, and deduce the download time (as a size/bandwidth rule of thumb).
This is interesting (and it works): https://github.com/sivel/speedtest-cli
