### ISSUE TITLE
Docs with Examples

### ISSUE THREAD

**Issue by rabitt** [mir-dataset-loaders/mirdata#18]
* Setup docs page (ghpages? readthedocs?).
* Add usage examples
* Docs for each dataset with a basic description of the dataset and links to the relevant websites. Especially focus on good docs for the data loaded in each dataset track object, e.g. `OrchsetTrack`.

**Comment by andreasjansson** [comment]
The way the Beam Python SDK does it is really nice, all code snippets are in a single file, with delimiters in comments:

https://github.com/apache/beam/blob/master/sdks/python/apache_beam/examples/snippets/snippets.py#L18-L31

This also means that examples can be tested in CI to make sure examples and code don't diverge, and examples are always runnable.

**Comment by rabitt** [comment]
Let's also add an FAQ section

**Comment by rabitt** [comment]
Done in #93 and #86
