### ISSUE TITLE
KeyData format vs key in mir_eval

### ISSUE THREAD

**Issue by magdalenafuentes** [mir-dataset-loaders/mirdata#184]
If I understand correctly in `mir_eval` [the key is global](https://craffel.github.io/mir_eval/#module-mir_eval.key), while KeyData is local (we have intervals of keys in time). Should we modify our data type or should keep it the same?

**Comment by lostanlen** [comment]
@magdalenafuentes I would support that. From what i understand of @rabitt's design, our `*Data` types ought to match `mir_eval`'s API reference closely. Being compatible is more important than being comprehensive.

However, for datasets with time-varing keys, I still think that the `to_jams` method must implement a key `Annotation` with time-duration-value-confidence elements.

**Comment by rabitt** [comment]
related - #195

**Comment by magdalenafuentes** [comment]
Will be addressed in #291

**Comment by rabitt** [comment]
Closed by #291
