### ISSUE TITLE
Throw warning when annotation path does not exist

### ISSUE THREAD

**Issue by rabitt** [mir-dataset-loaders/mirdata#196]
In our loaders, when an annotation path doesn't exist (e.g. for a dataset that hasn't been downloaded, or a nonexistent `data_home`), accessing the annotation silently returns `None`. We should probably throw a warning if the path doesn't exist. Thoughts?

**Comment by lostanlen** [comment]
in which function call should this warning be raised?

**Comment by rabitt** [comment]
In most `dataset.load_*` functions, we return None if the file doesn't exist, and the user has no idea.

**Comment by lostanlen** [comment]
@rabitt i'm revisiting this question today after hitting a filesystem mismatch.

I'm curious why you think this should be a warning by default? Why not an error? (potentially with a kwarg to circumvent it)

What's a reasonable use case in which the user would want to load a nonexistent annotation and be happy with `None`?

**Comment by rabitt** [comment]
> I'm curious why you think this should be a warning by default? Why not an error? (potentially with a kwarg to circumvent it)

Great point - I'd be in favor of throwing an `IOError`.

**Comment by rabitt** [comment]
@lostanlen shall we close this because of the duplicate issue in #222 ?

**Comment by lostanlen** [comment]
yes. many thanks for consdering my viewpoint
