### ISSUE TITLE
DALI and GTZAN_genre lack a `to_jams` method

### ISSUE THREAD

**Issue by magdalenafuentes** [mir-dataset-loaders/mirdata#197]

**Comment by rabitt** [comment]
Also gtazn_genre.to_jams is not implemented

**Comment by lostanlen** [comment]
I will address urgently.
Note that JAMS has a built-in namespace for GTZAN tags
https://github.com/marl/jams/blob/master/jams/schemata/namespaces/tag/gtzan.json

**Comment by rabitt** [comment]
The Gtzan half of this issue is fixed in #212
