### ISSUE TITLE
How should we handle big datasets?

### ISSUE THREAD

**Issue by rabitt** [mir-dataset-loaders/mirdata#20]
Right now we store the dataset index in the repo, and we load annotations into memory. This works OK for smaller datasets but won't scale to big ones. How should we handle this?

**Comment by lostanlen** [comment]
Is there any plan of making annotations interoperable with JAMS? If so, the annotations could be JSON-serialized to disk instead of kept in memory as Python objects.
For the index, this would boil down to https://github.com/marl/jams/issues/40

**Comment by lostanlen** [comment]
@rabitt what's the plan for this? `wontfix`?

**Comment by andreasjansson** [comment]
I submitted a [PR](https://github.com/mir-dataset-loaders/mirdata/pull/149) for an MSD loader yesterday with one proposal: Only store hashes of a random _x_% of the dataset, and if they are all correct there's a _y_% likelihood that all are correct. There's a trade-off between storage cost of _x_ and likelihood of dataset correctness _y_. In MSD's case I choose _x_=1%.

**Comment by rabitt** [comment]
@lostanlen not a wontfix. It's addressed in a combination of #149 and #128 so I closed this question :)
