### ISSUE TITLE
Groove MIDI dataset 

### ISSUE THREAD

**Issue by kyungyunlee** [mir-dataset-loaders/mirdata#206]
Hi! 
I would like to add [Groove MIDI dataset](https://magenta.tensorflow.org/datasets/groove) or the [Expanded Groove MIDI](https://magenta.tensorflow.org/datasets/e-gmd), if it will be of any help in the future. These have almost identical structure, so I could do both or either one of them. 

I don't think there is an example dataset that contains midi files, so I was wondering if there is a  suggested way to design a test for midi files. 
Is testing midi files (perhaps something analogous to `load_audio`) necessary? If so, should I be using something like the `pretty_midi` library? 

Thanks :)

**Comment by lostanlen** [comment]
Hello @kyungyunlee, welcome to mirdata!
Glad to hear that you are planning to add the Groove MIDI dataset. As you've noted, this would be our first dataset loader in MIDI format.

I would support implementing a `load_midi` method. I agree with you that using `pretty_midi` as a dependency makes perfect sense here. 
@magdalenafuentes and @rabitt: thoughts?

**Comment by kyungyunlee** [comment]
I am close to finishing a loader for Groove MIDI. 
Tests under py37 are all passing, but `pretty_midi` is not being installed during testing under py36. 
For now I added `pretty_midi` in `install_requires` in `setup.py`.

Should I be doing something more to ask tox to install pretty_midi? 
Any suggestions would be appreciated :)

**Comment by lostanlen** [comment]
> I am close to finishing a loader for Groove MIDI.

@kyungyunlee that's great to hear!

> Any suggestions would be appreciated :)

In this case, please start a pull request with a "[WIP]" ("work in progress") prefix so that we can provide feedback. It will also trigger a Travis continuous integration build.

**Comment by rabitt** [comment]
> I would support implementing a load_midi method. I agree with you that using pretty_midi as a dependency makes perfect sense here.
@magdalenafuentes and @rabitt: thoughts?

Yes, I agree!
