### ISSUE TITLE
TempoData and tempo_to_jams

### ISSUE THREAD

**Issue by lostanlen** [mir-dataset-loaders/mirdata#215]
Noted during CR of Groove MIDI #207 + an offline conversation with @rabitt 

Groove MIDI has some tempo annotations, which we can pull from the MIDI file via pretty_midi
It would be great if we had a mirdata type for this (`TempoData` ?) so that we can evaluate tempo estimators via mir_eval
It would also be great if we had a `tempo_to_jams` function in `jams_utils` so that we could pass a `tempo_data` kwarg to our `jams_utils.jams_converter`

**Comment by rabitt** [comment]
+1 !

**Comment by rabitt** [comment]
Working on this as part of #207

**Comment by rabitt** [comment]
Fixed in #207 . Note that I decided *not* to add a `TempoData` object, since it felt unnecessary, since (global) tempo is just a single numeric value.
