### ISSUE TITLE
dataset.choice

### ISSUE THREAD

**Issue by rabitt** [mir-dataset-loaders/mirdata#228]
An idea from #219 : would it be useful to add a `.choice()` method to each dataset module which returns one random instantiated Track object?

**Comment by lostanlen** [comment]
Yes. This is a nod to `random.choice` https://docs.python.org/3/library/random.html#random.choice

and i suspect it's going to be very useful for machine learning practictioners

It's also good for doing informal demos of mirdata

**Comment by rabitt** [comment]
Implemented in #296
