### ISSUE TITLE
groove_midi.load() fails

### ISSUE THREAD

**Issue by magdalenafuentes** [mir-dataset-loaders/mirdata#236]
The folder structure where `Groove MIDI` data is downloaded it's not right, now it's 
 `mir_datasets/Groove MIDI/Groove MIDI` but the loader expects the files to be one level up.

**Comment by magdalenafuentes** [comment]
@lostanlen you offered to do this fix, let me know if it's ok!

**Comment by lostanlen** [comment]
yes. do you prefer me to (1) unzip in .. and then rename the groove folder or (2) to move everything up one directory?

(1) is faster but assumes that the user has write access to os.path.split(data_home)[0]

vice versa for (2)

which do your prefer?

**Comment by magdalenafuentes** [comment]
I guess we don't want to download the zip in the `mir_datasets` folder right? If so, I think I prefer (2)

**Comment by rabitt** [comment]
Quick note to mention that the RemoteFileMetadata has an argument `destination_dir` precisely for this reason - I think you should be able to use this argument directly and not have to write any code yourself :)

https://github.com/mir-dataset-loaders/mirdata/blob/master/mirdata/download_utils.py#L21

**Comment by rabitt** [comment]
I'm thinking we should prioritize #234 in light of this before the full release...

**Comment by rabitt** [comment]
@lostanlen FYI I've assigned myself to this and am working on it now
