### ISSUE TITLE
Run `tests/test_full_dataset.py` on all existing datasets

### ISSUE THREAD

**Issue by rabitt** [mir-dataset-loaders/mirdata#241]
It will be a bit slow and painful, but we should run the `tests/test_full_dataset.py` script on all existing datasets to make sure there aren't any more secret bugs (e.g. #229 #236 #218 ) hiding in the library. 

Making a checklist here so we can keep track. Let's open new bugs if we run into any problems, and mark each one with ✅ or ❌ as we go.

- [ ] beatles
- [ ] dali
- [x] groove_midi ✅ ( @rabitt )
- [x] gtzan_genre ✅ ( @rabitt )
- [x] guitarset ✅( @magdalenafuentes )
- [x] ikala ✅ ( @rabitt )
- [x] medley_solos_db  ✅ ( @rabitt )
- [x] medleydb_melody ✅ ( @rabitt )
- [x] medleydb_pitch ✅ ( @rabitt )
- [x] orchset ✅ ( @rabitt )
- [ ] rwc_classical 
- [x] rwc_jazz ✅( @magdalenafuentes )
- [x] rwc_popular  ✅( @magdalenafuentes )
- [x] salami  ✅( @magdalenafuentes )
- [x] tinysol  ✅ ( @rabitt )

**Comment by magdalenafuentes** [comment]
Comment on this: @nkundiushuti proposed that we could run weekly checks in the server to make sure things aren't broken while we keep making changes to the library, which is a great idea. The list we have done so far is out-of-date already and would be too time consuming to do this periodically ourselves. Small datasets will be easy to check, and bigger datasets can be either partially downloaded and tested (e.g. if they have different remote objects in Zenodo) or can be checked in a monthly basis

**Comment by nkundiushuti** [comment]
I have prepared the script to launch tests weekly and monthly on our server and I am testing it 
I have managed to produced a report using the flag --html=report.html with the pytest-html extension
this currently produces reports for all basic tests in the tests directory
I want to include in this report the test_full_dataset results for a few datasets without producing other htmls

**Comment by magdalenafuentes** [comment]
That's amazing, thanks Marius! Just a few ideas: is it possible to put the report on a shared folder (Dropbox? Drive?) for the team to check? Maybe it would be useful if we could change the title depending on the result: report_ALL_PASSED vs. report_FAILED or something like that

**Comment by magdalenafuentes** [comment]
This will become irrelevant when #337 is finished, so closing it
