### ISSUE TITLE
rename the library?

### ISSUE THREAD

**Issue by rabitt** [mir-dataset-loaders/mirdata#25]
the name of the library is pretty clunky... got some great, prettier suggestions from @lostanlen:
* `mirabelle`: a small hardy European plum tree with finely toothed leaves and small cherry-shaped fruit
* `mireille`: Opéra in five acts by Charles-François Gounod. 1864
* `mirific`: (maɪˈrɪfɪk) achieving wonderful things or working wonders.
* `mirliton`: a generic term for Membranophone played by a performer speaking or singing into them, and which alter the sound of the voice by means of a vibrating membrane.

I like `mirliton`, personally. Other thoughts/opinions/ideas?

**Comment by keunwoochoi** [comment]
These are so @lostanlen 😄 

* `mir_xs`:  mir-related `x`'s (input~=audio's), pronounced as 'mir-access'
* `mir_xs2xs`: ok this is just a pun
* `mir_audio_retriever`: it's like golden retrievers (which are great)

**Comment by rabitt** [comment]
@andreasjansson suggests

`mirdl` / `mir_dl`: dl can be both "dataset loaders" and "download"

**Comment by lostanlen** [comment]
`mirdl` is difficult to pronounce and sounds like a rude word in French

**Comment by rabitt** [comment]
Thanks @lostanlen ! Turns out the same is also true in Spanish.

**Comment by rabitt** [comment]
@magdalenafuentes and I decided to go with the slightly square, but descriptive, `mirdata` as the repo name. Will change once #14 is merged. Thanks all for the suggestions
