### ISSUE TITLE
load_audio sample rate

### ISSUE THREAD

**Issue by rabitt** [mir-dataset-loaders/mirdata#251]
Our `load_audio` functions are almost all loading audio at 22050 Hz, which means librosa resamples almost every audio file on load. Should we do this? Should we use the native sample rate for most datasets?

**Comment by magdalenafuentes** [comment]
Mmmm.. I would go for the native sample rate, otherwise is unexpected for the user

**Comment by rabitt** [comment]
I agree. we're also not exposing the sample rate as a parameter since audio is a property and not a method. But we could port all `track.audio` methods to `track.get_audio(sr=None)`. It's a relatively big API change though

**Comment by magdalenafuentes** [comment]
Closing this since it is outdated
