### ISSUE TITLE
consolidate common load functions

### ISSUE THREAD

**Issue by rabitt** [mir-dataset-loaders/mirdata#257]
We have nearly identical code for things like "load_audio", "load_midi", etc across dataset loaders. Can we consolidate some of it? Should we use some of the built-in load functions in `mir_eval` as well?

**Comment by magdalenafuentes** [comment]
Mmmm.. don't know about this. One thing that is tempting is to add it to the `Dataset` class, but many datasets we aim to support in the future don't have audio. I'm not sure how to do this given the way `mirdata` is structured now

**Comment by magdalenafuentes** [comment]
@rabitt this feels outdated since we consolidated lots of things with the `Dataset`, `Track` and `Annotations` classes. I'll close it!
