### ISSUE TITLE
Add Slakh

### ISSUE THREAD

**Issue by rabitt** [mir-dataset-loaders/mirdata#263]
I'd like to add [Slakh](http://www.slakh.com/) to mirdata.

@ethman @pseeth - would you guys be able to help review if i do? Also, I've seen your companion repo [slackh-utils](https://github.com/ethman/slakh-utils) - it looks to me like the repo was mostly used to create the dataset. Is there functionality there that would make it worth having it as a dependency of mirdata?

**Comment by ethman** [comment]
Hey! Yes, I'd be thrilled to see it added. I would be able to help review. 

The slakh-utils repo was not used to create the dataset, but it does house a lot of common utilities for working with the dataset: resampling, converting to/from wav (the dataset is flac when you download it), making submixes, and moving files for different stratifications. To be honest, that repo could use some TLC but people have been using it okay for a while now. 

I do think there are some genuinely useful things in that repo for interfacing with the dataset, so perhaps it is worth including as a dependency. But some things seem more generalizable to other datasets, like resampling and flac/wav conversion--does mirdata support these things?

Let me know how I can help.

**Comment by rabitt** [comment]
Great, thanks @ethman ! Re. resampling/conversion, we don't currently support it, but I agree it seems like something that would be useful for many datasets. If it's "just" a matter of resampling, conversion & remixing, I'd (for perhaps obvious reasons!) add pysox as a dependency. which does all that.

I'll spend some time properly going through slakh-utils and see how it could integrate with mirdata!

**Comment by rabitt** [comment]
By the way, for downloading Slakh, I saw there's a google form you fill out, and the link is given after. Would you be OK with mirdata downloading directly from the link?

**Comment by ethman** [comment]
For resampling and conversion slakh-utils uses resampy and an ffmpeg-python respectively. I haven't used sox/pysox that much, but I assume the differences are negligible, correct?

As for remixing, all the mixes are instantaneous, so the stems just need to be added together. However, defining what stems go where within submixes requires a bit of logic. It wouldn't be difficult to translate it as is into mirdata, but it might be worth making the API a little bit better as the current one is suited for the command line.

> By the way, for downloading Slakh, I saw there's a google form you fill out, and the link is given after. Would you be OK with mirdata downloading directly from the link?

The form serves a few purposes. First, we want to keep track download stats but perhaps we could do that by hosting the data set on zenodo. I would have to talk with the co-authors at MERL about this, but I don't think it should be a problem. Second, we want to warn people that the download is ~100gb and the full data set is ~500gb uncompressed. It doesn't look like slakh would be the only large data set that mirdata supports, is the assumption that users know what they're getting into with a simple API call? We also have a small version that I use for debugging that I've been meaning to upload somewhere (affectionately called baby-slakh).
