### ISSUE TITLE
multiple versions for a dataset

### ISSUE THREAD

**Issue by nkundiushuti** [mir-dataset-loaders/mirdata#265]
It would be useful to be able to load or at least to check for different versions of a dataset:
- datasets may have corrections; zenodo allows for a new version of a dataset to be updated
- reproducibility: results are produced with a dataset at a version which may not be the most recent 

What are the implications on mirdata?
scenario 1. if a new feature/track/annotation is added/changed in a new version: the index has to be regenerated/ the code to regenerate the index is different for 2 versions/maybe the Track object should have different implementations for 2 different versions of a dataset 
scenario 2. if there are no major changes: some existing files are corrected e.g. some existing annotations, an existing audio file changed : then we don't need to change the content of the script to generate the index but we need to regenerate the index corresponding to a dataset (md5 may change for a changed file) 

Solutions

- it's easier to focus on scenario 2 for now 
- the script should generate indices for various dataset versions; this can be checked with zenodo
- the index should contain the version of the dataset 
- the dataset version should be a read-only attribute of Track 
- load method should have the dataset version as a parameter to check that we load the version we want 
- some datasets do not have versions: maybe we should not enforce dataset version but rather allow for it

**Comment by rabitt** [comment]
Hey @nkundiushuti 

I agree we should start by focusing on scenario 2. I like the idea of allowing (but not requiring) a version field in the index, which could allow the user to specify which version of the index to load.

Related issue - #153 - we've discussed how to handle the ever growing size of the indexes that are versioned here, and we'd like to move everything to e.g. git lfs, which will help support this idea of multiple dataset versions. What do you think?

**Comment by nkundiushuti** [comment]
great idea! so should we have different indexes for different versions stored there?

**Comment by magdalenafuentes** [comment]
Yes, exactly. Also add the version as an optional value in the index as you suggested, and modify the loader to be able to switch between versions. We will be working in #153 by the end of the year for the next release

**Comment by nkundiushuti** [comment]
this is great! so only dataset metadata and not track metadata is stored in the index?

**Comment by magdalenafuentes** [comment]
Now we don't check metadata's checksums, so the idea is to verify that as well the same way we're doing with the tracks. Also, by adding the keys in the index (which will be optional), we'll be able to incorporate `multitracks` and `tables` easily (#295, #272). This will close #277
