### ISSUE TITLE
Track .to_jams support for multiple audio files/events

### ISSUE THREAD

**Issue by nkundiushuti** [mir-dataset-loaders/mirdata#266]
I have a question regarding to_jams conversion for a Track which has multiple audio files and multiple EventData. Namely, audio and scores for multiple instruments. How is it possible to convert to jams such a track? 
Is exporting to jams really needed if we offer the data through class? I am not familiar with this file format and maybe it is not really used/useful. Here in MTG we use YAML instead of JSON. It would be great to have that but that's another story.  

At the moment I am doing this:
```
  def to_jams(self):
        """Jams: the track's data in jams format"""
        score_data = [(self.targets[target].score, 'score-'+target) for target in self.targets]
        original_score_data = [(self.targets[target].original_score, 'score-'+target) for target in self.targets]
        metadata = {}
        metadata['instruments'] = self.instruments
        metadata['sections'] = self.sections
        metadata['sources'] = self.sources
        metadata['targets'] = self.targets
        audio_paths = [os.path.join(self.audio_path,source+'.wav') for source in self.sources.keys()]
        return jams_utils.jams_converter(
            event_data=score_data.extend(original_score_data),
            metadata=metadata,
        )
```
it doesn't add any annotation.

**Comment by rabitt** [comment]
It looks like you've written the converter the right way, and that should work. If it doesn't add annotations (how are you seeing that?) then there may be a bug in the jams_converter itself. Is this part of your PR? If so we can investigate further!

**Comment by nkundiushuti** [comment]
sorry Rachel. the problem was not with the multiple annotations. I managed to fix that in the latest commit corresponding to the PR. the problem is with multiple audio files for a track. I don't know how to put that in jams format.

if I try to return:

```
return jams_utils.jams_converter(
            audio_path=audio_paths,
            event_data=score_data + original_score_data,
            metadata=metadata,
        )
```

then I get is in mirdata/jams_utils.py:77: in jams_converter
    if os.path.exists(audio_path):

```
path = ['tests/resources/mir_datasets/PHENICX-Anechoic/audio/beethoven/bassoon1.wav', 'tests/resources/mir_datasets/PHENICX-A...ic/audio/beethoven/clarinet2.wav', 'tests/resources/mir_datasets/PHENICX-Anechoic/audio/beethoven/doublebass.wav', ...]

    def exists(path):
        """Test whether a path exists.  Returns False for broken symbolic links"""
        try:
>           os.stat(path)
E           TypeError: stat: path should be string, bytes, os.PathLike or integer, not list
```

it expects the path as a string

**Comment by rabitt** [comment]
You're right - jams doesn't play nicely with multiple audio files. The quick fix is to pass it just one audio file, but I think we nee a longer-term fix. I've opened #276 to discuss, and I'm going to close this issue!
