### ISSUE TITLE
 SymbolicData structure  [enhancement]

### ISSUE THREAD

**Issue by PRamoneda** [mir-dataset-loaders/mirdata#267]
The next dataset loader that we are going to implement is composed of symbolic information with annotations. We are thinking about the humdrum format to implement the symbolicdata structure. We are open to other formats to standardise future mirdata loaders with symbolic information.

Thank you very much

**Comment by magdalenafuentes** [comment]
This is a good question, and will require a little discussion on our side. Will come back to you asap.

**Comment by PRamoneda** [comment]
Hi @magdalenafuentes !!

 We have been talking with @napulen the author of Haydn quartets op20 dataset and with other group members. The most used options available for symbolic notation are three:  MusicXML, Humdrum, y MEI. 
Are you already discussing that?

Other problem would be that Track class wouldn't be the central axis of the loader (moreover that current testes can't be done without audio tracks).

**Comment by rabitt** [comment]
I'm not that familiar with the symbolic formats either, but the midi parallel in mirdata is for example in groove_midi:

`Track.midi` -- a prettyMIDI object containing all midi data
`Track.drum_events` -- a EventData object containing just the drum transcription events
... other things parsed from the midi ...

I can imagine something similar for the symbolic case - a generic container for everything in e.g. xml/humdrum, and if there's a specific task that is being addressed in the dataset, it can be further parsed into whatever data object makes sense. What do you think?

**Comment by PRamoneda** [comment]
Ok, perfect. Then, which format do you think that would be better for Mirdata? MusicXML or Humdrum?

**Comment by rabitt** [comment]
I don't have a strong opinion - @PRamoneda which one do you think is more common / has better supported python libraries?

**Comment by PRamoneda** [comment]
Python Music21 library is the most used on symbolic domain. And it supports both 😅. Most scores are in xml. However, most of computational musicology (in chords and structural analysis) datasets are in humdrum. That’s why I would use humdrum.

**Comment by rabitt** [comment]
Does Music21 have a data structure that both humdrum and music xml formats could be loaded into?

**Comment by nkundiushuti** [comment]
one thing we should take into account is that to_jams validation may fail if no audio is present. the duration attribute is taken from the audio.

**Comment by PRamoneda** [comment]
Hi @rabitt  we are thinking about another dataset. 
[The acoustic brainz genre dataset](https://julian-urbano.info/files/publications/016-acousticbrainz-genre-dataset-multi-source-multi-level-multi-label-large-scale.pdf). (there are 4 different datasets inside this project).
To sum up, each track has some features computed on the original audio. But the original audio is not available because it is proprietary and there are about 2 million tracks among the 4 datasets. I think we're going to have the same problem that @nkundiushuti mentioned with the tests.

**Comment by rabitt** [comment]
I've just opened #282 about the duration issue!

To follow up on the earlier discussion - 
> Does Music21 have a data structure that both humdrum and music xml formats could be loaded into?

@PRamoneda @nkundiushuti ?

**Comment by magdalenafuentes** [comment]
About the issue of availability in tracks for tests. @PRamoneda I'm not sure if I'm following, but we already have some other datasets with no available audio (like `Beatles` or the `RWC collection`). In those cases in the tests we upload one track that we have in our local dataset copies. It's a bit on the edge but is only one track and for testing purposes, so I would do the same in those cases you mentioned. 

Does this make sense or did I get it completely wrong?

**Comment by magdalenafuentes** [comment]
About creating a symbolic data type. Depending on what we decide in #282, we might modify the `Track` object to support symbolic data. If so, as @rabitt mentioned before, could we add attributes that make sense on the `symbolic domain` such as `Track.midi` or `Track. humdrum` instead of creating a new class? Does this make sense?

**Comment by PRamoneda** [comment]
This framework have been proposed in symbolic domain :S. But only focusing on music generative tasks

https://program.ismir2020.net/poster_1-12.html.

**Comment by PRamoneda** [comment]
BTW this dataset seems very nice:

https://github.com/music-x-lab/POP909-Dataset

**Comment by rabitt** [comment]
To close this issue, as we've discussed offline:
1. We will not create a new symbolic data structure, instead we'll use the existing `Track` class.
2. We're OK having a music21 dependency in mirdata to support file formats like humdrum
3. We're considering either not supporting purely symbolic datasets / working with the muspy library to handle symbolic data (#298 )
