### ISSUE TITLE
MetreData and MainKeyData [enhancement]

### ISSUE THREAD

**Issue by PRamoneda** [mir-dataset-loaders/mirdata#268]
We are developing loaders for [JAAH dataset](https://github.com/MTG/JAAH). There are two data structures that we need and we can add. MetreData and MainKeyData.
```Python
MetreData = namedtuple('MetreData', ['numerator', 'denominator'])

MainKeyData = namedtuple('MainKeyData', ['tonal degree', 'modality'])

```

**Comment by magdalenafuentes** [comment]
Hey @PRamoneda, looking forward to having the JAAH dataset!

It seems to me that the `MeterData` type is a good idea. I wonder if the `MainKeyData` overlaps with the already existing`KeyData` type? E.g. if you set a `KeyData` object with start and end of the track to indicate is the main key?

**Comment by PRamoneda** [comment]
Yeah, but on the one hand, you would be overlapping two concepts. Maybe the main tonality is CM but you have modulations to other keys int he track. However,  JAAH dataset only has the main key.

On the other hand, start and end are not needed.

However, maybe is better to return the mainkey as a string (JAM metadata)

**Comment by magdalenafuentes** [comment]
After a bit more discussion on this: our approach so far has been to create a data structure if the annotation is sequential (e.g. `key` changes over time so the `start` and `end` times make sense). When the annotations is the same for the entire track, we include it as `metadata`. However, it is an open discussion (see #233) what to do with things that apply globally to the track. For now the recommendation would be to includit as a global/metadata attribute.

What are your thoughts about it?

**Comment by PRamoneda** [comment]
I think is perfect!!
