### ISSUE TITLE
dataset_loader.search_audios(path) function [enhancement]

### ISSUE THREAD

**Issue by PRamoneda** [mir-dataset-loaders/mirdata#269]
We believe that it would be essential to create a function that would detect audios regardless of the name or the directory structure.

To do this, we would only have to analyse the md5 of all the files in the directory recursively. And see if any of them match the list of audios.

 The way to obtain the audios is very heterogeneous for a MIR researcher.

What is your opinion?  

Thank you very much.

**Comment by magdalenafuentes** [comment]
Interesting idea, can you explain a little bit more the motivation?

Right now as `mirdata` is the datasets are organized following a rigid pre-defined structure which facilitates verification and loading, but I guess you're thinking of another application? Like having a helper function to find a-priori disorganized audios?

**Comment by PRamoneda** [comment]
`Like having a helper function to find a-priori disorganized audios?` Yeah, that would be the idea.

The motivation is that the file name is not the same that the annotated name in some datasets. Spaces are _ or quotes are removed. Moreover, some Datasets as MTG-JAAH or USPOP2002 doesn't use all the songs from the CDs. And is easy to get a CD from a library or from ~torrents~. I am thinking about small research groups or in a random student from a university without a Music Technology group. Where you can not get the audios easily.

**Comment by magdalenafuentes** [comment]
The problem of naming files is part of what we tried to solve with the validation, which checks for this typos and also differences in audio, and the way around it is changing the file names to match those of the indexes. However, if you're concern about people not knowing the matching and having to parse it manually, building a function for that is a harder problem and I'm not sure how to support it and make it general. Did I understand your point?

**Comment by rabitt** [comment]
I'm going to close this for now, as we're focusing as much as possible on openly available datasets. We can reopen in the future if this comes up!
