### ISSUE TITLE
Jupyter notebook examples.

### ISSUE THREAD

**Issue by PRamoneda** [mir-dataset-loaders/mirdata#271]
We have been discussing and we want to include some examples in each dataset loader. Where is a good place to include these notebooks?

Maybe a new directory?

Thank you so much!!!

**Comment by rabitt** [comment]
We'd love to have more examples for each loader! I think the best place for it would be in the documentation. We have an [examples section](https://mirdata.readthedocs.io/en/latest/source/example.html) now, but it could be expanded / we could add another section. We alternatively could put examples [at the top of each dataset's documentation](https://mirdata.readthedocs.io/en/latest/source/mirdata.html#module-mirdata.beatles)

This should make it easy to copy-paste working code into a notebook, a script, or wherever!

**Comment by PRamoneda** [comment]
Hi @rabitt! 
Our idea is to upload a jupyter notebook with each use case. Could we create a directory `examples` where set the notebooks??

**Comment by rabitt** [comment]
I like the idea a lot, but I'm personally not a fan of jupyter notebooks as part of this library - could we have the exact same code/examples that you'd want to put in the notebooks, but instead put it directly in the documentation? For example, we have something similar in the [documentation examples here](https://mirdata.readthedocs.io/en/latest/source/example.html)? We could make a full section in the docs for dataset-specific examples, and even set up automatic testing of the "code" in the docs to make sure it's runnable.

**Comment by PRamoneda** [comment]
I think that would be important to restructure the documentation a bit in the future.

Maybe you could create a new repo on mir-dataset-loader. We PR the notebooks to there and quote from mirdata documentation :)

We love colabs and jupyters and there are some nice examples at MIR community such as https://www.audiolabs-erlangen.de/resources/MIR/FMP/C0/C0.html.

What's your opinion about it?

**Comment by rabitt** [comment]
> I think that would be important to restructure the documentation a bit in the future.

Happy to hear any thoughts about how to improve the documentation!

> Maybe you could create a new repo on mir-dataset-loader. We PR the notebooks to there and quote from mirdata documentation :)

Sure, that's a good idea! I can start that now. 

> We love colabs and jupyters and there are some nice examples at MIR community such as https://www.audiolabs-erlangen.de/resources/MIR/FMP/C0/C0.html.

Yes, this is a great project, and we've actually spoken with them about integrating some mirdata examples there as well. Maybe this mirdata-notebooks repo can be the starting point :)

**Comment by rabitt** [comment]
@PRamoneda @nkundiushuti I just gave you both write access to [mirdata-notebooks](https://github.com/mir-dataset-loaders/mirdata-notebooks). Feel free to add what you want!

**Comment by magdalenafuentes** [comment]
I love this solution!

**Comment by magdalenafuentes** [comment]
If you agree I'm closing this one
