### ISSUE TITLE
Demo gif is confusing

### ISSUE THREAD

**Issue by bmcfee** [mir-dataset-loaders/mirdata#279]
Hey mirdataers!

I finally gave this a spin, and eventually figured out how to use it. (Awesome!)

However, the animated gif in the readme is confusing, as the code snippet wouldn't actually work.  It took me a while to figure out that the datasets need to be imported explicitly, but this step is omitted from the demo.  (Also it skips the download step!)

As an aside, there was no way to pause the gif, so it was a not-so-great experience trying to read it quickly enough to figure out what I was doing wrong.  GIFs in general aren't great for accessibility, so I humbly suggest to replace it by a self-contained text snippet.

**Comment by rabitt** [comment]
Great point, I'll remove it!
