### ISSUE TITLE
Extend Contributing explaining better data types

### ISSUE THREAD

**Issue by magdalenafuentes** [mir-dataset-loaders/mirdata#284]
1. We should explain how we use data types because it's not obvious (e.g. list of BeatData vs. BeatData containing arrays of beat times and positions).
2. We should clarify that we follow `mir_eval` conventions, for contributors adding new data types.
3. Convention is: if annotation doesn't change over time is part of metadata (e.g. genre->str) and if it does change thenb it becomes a data type

**Comment by rabitt** [comment]
This will be partially solved by #291 !

**Comment by magdalenafuentes** [comment]
Moved this to #245
