### ISSUE TITLE
Non-audio dataset with available spectrum (cante100/COFLA)

### ISSUE THREAD

**Issue by genisplaja** [mir-dataset-loaders/mirdata#287]
Hello! We are implementing the loader for the [cofla100 dataset](http://www.cofla-project.com/?page_id=529&lang=es). The special fact about this dataset is that the audio is just available upon request, but the spectrum of the tracks is available together with the annotations. 
If you refer to [my branch of the cante100 loader](https://github.com/mir-dataset-loaders/mirdata/tree/genis/cante100), you can see the implementation of the loader for cante100. We propose to load the spectrum instead of the audio. At the end of the day, importing the spectrum is as useful as importing the audio. By the way, the loader is passing all the tests!
Hope you find this proposal interesting!

**Comment by rabitt** [comment]
Nice! I think it's totally fine if we load the spectrum, and if the download default just downloads the spectrum + annotations. What about also supporting the data (with a load function and an attribute), but putting something in the download with instructions for how to request it? we have something similar for e.g. the beatles dataset, which has an open download for the annotations but closed for the audio.

**Comment by genisplaja** [comment]
Ok! I thinks it's a good idea to support audio loading as well. I will implement it and make the PR. Thanks for the feedback!

**Comment by magdalenafuentes** [comment]
Closed via #317
