### ISSUE TITLE
IRMAS Dataset integration

### ISSUE THREAD

**Issue by genisplaja** [mir-dataset-loaders/mirdata#289]
Hello! I've just created a [PR for the IRMAS Dataset loader](https://github.com/mir-dataset-loaders/mirdata/pull/288).

The [IRMAS Dataset](https://zenodo.org/record/1290750#.X4ltDdbgqu6) is aimed at contributing to works on predominant instrument(s) detection. The main issue with this dataset is that it's split into train/test samples and that training tracks are different annotated than testing tracks. Annotations themselves are different as well.
- Training track: annotations are in the file name. There is information about a single predominant instrument, the genre, and some tracks have a flag to know if there is drum presence or not.
- Testing track: annotations are in a separate .txt file with the same name as the audio track. The annotations contain one or more predominant instruments in the track. There is no information about the genre or the drum presence.

The proposed strategy to approach this loader is based on creating a metadata dictionary in the _load_metadata function by going through the dataset contents, as there is no "general" metadata file. Then the predominant instrument (which is the important annotation here) is retrieved with a specific function and stored as EventData. You can refer to the [IRMAS loader branch](https://github.com/MTG/mirdata/tree/genis/irmas_2) to see the whole implementation in detail. Thanks!!

**Comment by magdalenafuentes** [comment]
Closed via #288 (or #320 ?)
