### ISSUE TITLE
NamedTuples --> Classes

### ISSUE THREAD

**Issue by rabitt** [mir-dataset-loaders/mirdata#291]
Annotations are currently defined as NamedTuples (e.g. F0Data) or as Track attributes. In order to better support searching & standardization, we've discussed moving them over to Classes, where we can support:
* mir_eval compatibility (#195 )
* data type and unit consistency
* format conversion
* (eventually) automatic JAMS support (related to #316 , #224)

This should be backward compatible.

**Comment by magdalenafuentes** [comment]
Also creating separated files for the data types / annotations
