### ISSUE TITLE
Dataset.info()

### ISSUE THREAD

**Issue by magdalenafuentes** [mir-dataset-loaders/mirdata#300]
Related to #294 we decided that it would be good to have a `Dataset.info` which will show what annotations are in the dataset, and could be reused in a search function #176  and generators #297 .

**Comment by rabitt** [comment]
This will be great to add once #296 is merged!

**Comment by nkundiushuti** [comment]
we should consider adding a license information for the dataset when this is available. maybe in the info function

**Comment by magdalenafuentes** [comment]
Done in #408 and #410
