### ISSUE TITLE
unzip cp437 filename encoding issue

### ISSUE THREAD

**Issue by nkundiushuti** [mir-dataset-loaders/mirdata#306]
we have a problem in IRMAS because it seems that the archive has been created within Windows with a cp437 encoding. this means that with ziplib some filenames containing utf8 chars (umlauts for instance) aren't decoded properly and these files cannot be read properly. the test_full_dataset fails for irmas at the moment

there are 2 solutions
1. we upload a new version of IRMAS with new zip files
2. we modify unzip and replace extract all to support cp437 encoding for all zip archives

```

def extractall_unicode(zf,zdir):
    for m in zf.infolist():
        data = zf.read(m) # extract zipped data into memory

        if m.filename.encode('cp437').decode() != m.filename.encode('utf8').decode():
            disk_file_name = os.path.join(zdir,m.filename.encode('cp437').decode() )
        else:
            disk_file_name = os.path.join(zdir,m.filename)
    
        dir_name = os.path.dirname(disk_file_name)
        if not os.path.exists(dir_name):
            os.makedirs(dir_name)

        if os.path.isfile(disk_file_name):
            with open(disk_file_name, 'wb') as fd:
                fd.write(data)

def unzip(zip_path, cleanup=True):
    """Unzip a zip file inside it's current directory.

    Args:
        zip_path (str): Path to zip file
        cleanup (bool): If True, remove zipfile after unzipping. Default=False

    """
    zfile = zipfile.ZipFile(zip_path, 'r')
    #zfile.extractall(os.path.dirname(zip_path))
    extractall_unicode(zfile,os.path.dirname(zip_path))
    zfile.close()
    if cleanup:
        os.remove(zip_path)

```

@genisplaja

**Comment by rabitt** [comment]
@nkundiushuti I suspect this wont be the only time we run into this problem for a dataset, so I'd go for the second solution. The one tricky thing is to make sure it doesn't introduce new bugs for existing loaders - we should run `test_full_dataset` for a few different loaders that use zip to make sure. 

Feel free to open a PR and I'll review!
