### ISSUE TITLE
Saraga dataset - pycompmusic dependency

### ISSUE THREAD

**Issue by nkundiushuti** [mir-dataset-loaders/mirdata#308]
@genisplaja is working towards adding Saraga dataset which is stored in MTG's dunya https://dunya.compmusic.upf.edu 
the Saraga files are stored in zenodo, except the multi-track. 
to get the multi-track we have two options
1. upload them to zenodo :) 
advantages:
- faster download 
- sustainability
- no extra dependency on pycompmusic
2. extend the download function in the Saraga class and download the files from dunya
This involves adding pycompmusic as a dependency 
advantages:
- pycompmusic is quite a light dependency, maintained by MTG: https://github.com/MTG/pycompmusic/blob/master/requirements.py3.txt
- we can reuse this to other datasets in dunya 
disadvantages:
- API issues: what is the limit of the requests we can make through dunya? does dunya allows for simultaneous downloads of the dataset using the same API key ?

**Comment by rabitt** [comment]
@nkundiushuti is pycompmusic the only way to access the full datasets in dunya? Or are they mostly duplicated on e.g. zenodo? If they're duplicated I'd go with the zenodo option. I lean away from the extra dependency, but if it will make download easier for a bunch of datasets it could be worth it!

**Comment by nkundiushuti** [comment]
apparently we can do without pycompmusic just querying dunya:
https://github.com/MTG/pycompmusic/blob/master/compmusic/dunya/docserver.py#L135
a request to dunya.upf.edu/document/by-id/[mbid]/filetype, sent with a header 'Authorization' to authenticate as the user with their token
@genisplaja could you check this at some point? 
you need to use these functions:
https://dunya.compmusic.upf.edu/docs/_modules/compmusic/dunya/conn.html

**Comment by magdalenafuentes** [comment]
@genisplaja this is done right? Saraga is in master already. Can you confirm and close this issue?

**Comment by genisplaja** [comment]
Yes, this issue can be closed at the moment. However, [Dunya](https://dunya.compmusic.upf.edu/) has several corpuses of different non-western music styles, so maybe we will need to re-open it at some point, but we won't need this for the Saraga implementation anymore. I got access to the multitrack part, so I will upload it to Zenodo and download it from there in the Saraga-Multitrack loader.
