### ISSUE TITLE
beatport key bad index

### ISSUE THREAD

**Issue by PRamoneda** [mir-dataset-loaders/mirdata#311]
I have found an error. Index doesnt have all the keys.

I am sorry.

**Comment by PRamoneda** [comment]
done here: https://github.com/mir-dataset-loaders/mirdata/pull/312

**Comment by rabitt** [comment]
no problem! thanks for catching it!

**Comment by PRamoneda** [comment]
done here!
https://github.com/mir-dataset-loaders/mirdata/pull/312
