### ISSUE TITLE
JAMS and mir_eval non compatible datasets

### ISSUE THREAD

**Issue by magdalenafuentes** [mir-dataset-loaders/mirdata#316]
In some cases the annotations of a dataset are not compliant with `JAMS` validation oir `mir_eval` format, not because of mistakes but other reasons such as the annotations are more complex or from a music stye or task not contemplated yet.

There are workarounds such as adding annotations as metadata instead, but since this will likely happen with more datasets, maybe we should think what to do in this cases. One example is #312.

**Comment by magdalenafuentes** [comment]
Related to #233 and #291

**Comment by rabitt** [comment]
Closed by #291
