### ISSUE TITLE
indexes in setup.py in 0.3b version

### ISSUE THREAD

**Issue by nkundiushuti** [mir-dataset-loaders/mirdata#321]
shouldn't it be:
` package_data={"mirdata": ["datasets/indexes/*"]},`
instead of
` package_data={"mirdata": ["indexes/*"]},`

**Comment by rabitt** [comment]
Shoot you're right!! Good catch. This is why we have beta versions 😂

**Comment by rabitt** [comment]
Happy to push a fix, but feel free to do it if you get to it first

**Comment by rabitt** [comment]
closed by #322
