### ISSUE TITLE
Regularly check if links for downloading data are online

### ISSUE THREAD

**Issue by magdalenafuentes** [mir-dataset-loaders/mirdata#34]
Just discussed with @rabitt about this. We are using several links to download data, we should check regularly if they are `online`. Is it possible to write a test on that?

If a link goes `offline`, one idea is to write a function that checks links when calling download, and gives a `temporarily offline` message or so. What do you think?

**Comment by tkell** [comment]
Hmm, there are a few ways to do this!

- We could check in CircleCI if the files still exist ... but that is a bit odd because our build would not pass if someone else removes a file.
- We could add a script that makes a HEAD request to each file and confirms that they're there.
- We could modified `download_from_remote` to check for a `URLError` and get out accordingly.  

What do you think?

**Comment by rabitt** [comment]
I actually think a combination of all three could make sense! (3) seems like a good thing to have in general. Could we do both (2) and (3), and have a separate CircleCI process (i.e. (1)) that runs (2), which checks for (3)?

**Comment by tkell** [comment]
kk!  I will start on this stuff!

**Comment by tkell** [comment]
- [ ] Add a `check_remote` function to `utils.py` that makes a HEAD request and returns True or False
- [ ] Write a test that makes this call for all datasets
- [ ] Automate this test with Circle, but _don't fail the build_ if it fails.

**Comment by drubinstein** [comment]
Can we just put on the README.md some embedded javascript or a shield from https://shields.io/ showing whether or not the link is live?

**Comment by rabitt** [comment]
Update - after discussing with @tkell and @drubinstein we decide we won't regularly check links, but instead, report to the user if a link is broken. If it is, we ask the user to report it on our issues page with the flag `broken-link`.

**Comment by rabitt** [comment]
Fixed in #53
