### ISSUE TITLE
bug mridangam test_full 

### ISSUE THREAD

**Issue by nkundiushuti** [mir-dataset-loaders/mirdata#346]
Failed | tests/test_full_dataset.py::test_validation | 0.61 |  
skip_remote = None
dataset = The mridangam_stroke dataset
-----------------------------------------------------------------------------------------... in the Track
    ----------------------------------------------------------------------------------------------------

    def test_validation(skip_remote, dataset):
        if dataset is None:
            pytest.skip()
    
        # run validation
        missing_files, invalid_checksums = dataset.validate(verbose=True)
    
>       assert missing_files == {key:{} for key in dataset._index.keys() if not key == "version"}
E       AssertionError: assert {'tracks': {}} == {'metadata': {}, 'tracks': {}}
E         Omitting 1 identical items, use -vv to show
E         Right contains 1 more item:
E         {'metadata': {}}
E         Use -v to get the full diff

tests/test_full_dataset.py:48: AssertionError

**Comment by genisplaja** [comment]
Thanks for the note! I think this issue should've been solved with @magdalenafuentes' fix #342. Last week, I found that same issue for Mridangam and other datasets as seen in #341. Is the error persisting? Or the test was running to an older version of the dataset loader and index. I will check it right now in the master code!

**Comment by genisplaja** [comment]
As you can see here: [https://github.com/mir-dataset-loaders/mirdata/blob/master/mirdata/datasets/indexes/mridangam_stroke_index.json](https://github.com/mir-dataset-loaders/mirdata/blob/master/mirdata/datasets/indexes/mridangam_stroke_index.json) (with this link you can see the Mridangam index in the current master branch), there is no `metadata` key in the index, so maybe the test was running over an older version of the Mridangam Dataset. I will run now the `test_full_dataset` in my machine to double-check it!

**Comment by nkundiushuti** [comment]
sorry this was fixed. the master on the test machine was not up to date
