### ISSUE TITLE
Reduce size of audio files in test/resources

### ISSUE THREAD

**Issue by magdalenafuentes** [mir-dataset-loaders/mirdata#360]
To do and to keep in mind after the release:

- Cut audio test files to a few seconds
- Update `CONTRIBUTING.md` to remind future contributors to do this

Otherwise our resources folder will rapidly be out of control.

- [x] giansteps_key
- [x] giantsteps_tempo
- [x] tonality_classicaldb
- [x] beatport_key
- [x] cante100
- [x] irmas
- [x] saraga_carnatic
- [x] saraga_hindustani

**Comment by PRamoneda** [comment]
Ok! I will do it tomorrow!!
