### ISSUE TITLE
Docs Tutorial

### ISSUE THREAD

**Issue by rabitt** [mir-dataset-loaders/mirdata#364]
(When #363 is merged)

Hey @PRamoneda @genisplaja - @magdalenafuentes put together an outline for the tutorial in source/tutorial.rst, and I left the examples.rst (but its removed from the docs now) in case you want to copy anything from it. You can remove examples.rst when you're finished.

**Comment by magdalenafuentes** [comment]
Following up on this, these loader docs should be fixed:

- [ ] Review docs of current loaders and fix when problems
    - [ ] AcousticBrainz
    - [ ] Cante100
    - [ ] Mridangam_stroke
    - [ ] tonality_classicaldb

**Comment by rabitt** [comment]
@magdalenafuentes I already fixed a bunch of the issues here, but good to double check them in case I missed things.

**Comment by genisplaja** [comment]
It's OK for me! I will double-check it while having in mind the Google formatting mentioned in #365. Thanks for all the changes @rabitt and @magdalenafuentes!!

**Comment by rabitt** [comment]
This is closed by #378
