### ISSUE TITLE
Dataset object per loader

### ISSUE THREAD

**Issue by rabitt** [mir-dataset-loaders/mirdata#366]
I'm going to quickly experiment with defining an instance of a dataset object for each loader (an option we talked about in #296 ) and see how the docs look. Right now the docs for each dataset module are very confusing because they don't obviously show all the needed functionality (.download, .cite, etc) since these get inherited from the dataset object.

Will try to do this tomorrow to not block the docs updates.

**Comment by rabitt** [comment]
FYI @genisplaja and @PRamoneda I'm checking this today, and if we go this way, every loader is going to change again 🙃 , but I guess better now than after the big change!

I'm hoping this will greatly improve the docs/clarity of the API. Happy to have your comments on the PR :)

**Comment by genisplaja** [comment]
Ok! No problem @rabitt:) Tomorrow morning I will check it out!!

**Comment by rabitt** [comment]
Closed by #377
