### ISSUE TITLE
Use csv module for data loading

### ISSUE THREAD

**Issue by rabitt** [mir-dataset-loaders/mirdata#372]
Hey @PRamoneda @genisplaja ! (none of this is urgent, just wanted to open so I don't forget!) 

I noticed this as I was going through some of the loaders and I have a general suggestion. When loading a file spaced by commas, tabs, etc, we should use the `csv` library to load it instead of parsing it manually. 

For example, in saraga_carnatic, you have this code:
```python
def load_phrases(phrases_path):
     ...
    with open(phrases_path, 'r') as reader:
        for line in reader.readlines():
            start_times.append(float(line.split('\t')[0]))
            end_times.append(
                float(line.split('\t')[0]) + float(line.split('\t')[2])
            )
            if len(line.split('\t')) == 4:
                events.append(str(line.split('\t')[3].split('\n')[0]))
            else:
                events.append(' ')
```

it could be replaced by:
```python
def load_phrases(phrases_path):
     ...
    with open(phrases_path, 'r') as fhandle:
        reader = csv.reader(fhandle, delimiter='\t')
        for line in reader:
            start_times.append(float(line[0]))
            end_times.append(
                float(line[0]) + float(line[2])
            )
            if len(line) == 4:
                events.append(str(line[3].split('\n')[0]))
            else:
                events.append(' ')
```

**Comment by genisplaja** [comment]
Cool! I will revise together with the docs. I will focus on my loaders at the moment:

- [ ] Saraga Carnatic
- [ ] Saraga Hindustani
- [ ] cante100
- [ ] IRMAS
- [ ] Mridangam Stroke

**Comment by rabitt** [comment]
I quickly checked for any remaining. The rest are quite minor!

- [ ] beatport_key (load_key)
- [ ] cante100 (load_f0, load_notes) *this one uses np.genfromtext, it's not a bad solution, but maybe we should have everything use csv for consistency
- [ ] irmas (load_pred_instrument)
- [ ] tonality_classicaldb (load_key)

**Comment by PRamoneda** [comment]
ok!!
