### ISSUE TITLE
docs for remote index

### ISSUE THREAD

**Issue by rabitt** [mir-dataset-loaders/mirdata#380]
In acousticbrainz_genre, the Track object is missing docs for how the remote index should be used. @PRamoneda in #377 I changed the dataset object, and we'll need to discuss how to plug in the remote index functionality.

**Comment by PRamoneda** [comment]
ok!!

**Comment by PRamoneda** [comment]
I am thinking about this @rachel. The user doenst know that the dataset is remote.... Then, it is no need for adding it in the documentation....

**Comment by rabitt** [comment]
I think this is done! I moved your documentation on remote indexes from the tutorial into contributing, since as you say @PRamoneda the regular users don't need to know its remote!

going to close this issue :)
