### ISSUE TITLE
Annotation types and annotations API

### ISSUE THREAD

**Issue by magdalenafuentes** [mir-dataset-loaders/mirdata#382]
Remove redundancy

**Comment by magdalenafuentes** [comment]
@rabitt I'm unsure about this. I started modifying the table, basically moving the definitions to the docs in `annotations.py` (which seems to make sense!), but I don't know how to link the data types to the generated docs, e.g. `Beats` in the `Annotation Types` column to the corresponding `annotation type` definition in the `API`. Do you know if that's possible? Or thoughts about it?

**Comment by rabitt** [comment]
I have to say that I like having the descriptions there with the table. What about the .readme solution like for the datasets? we could have a method for each annotation object that prints a link to that part of the docs?

**Comment by magdalenafuentes** [comment]
Yeah, also it's simpler to leave the annotations there. The only issue is that we have to update things in two places when we add more annotations, but it's not a big deal. I'll leave the description there and just fix a few things in the table (like adding links for each dataset as the description says)
