### ISSUE TITLE
Fill in TODOS in docs

### ISSUE THREAD

**Issue by rabitt** [mir-dataset-loaders/mirdata#388]
If you search the code, there are a few TODOs in the docs - we should fill them in

**Comment by magdalenafuentes** [comment]
Just seen this, will take a look

**Comment by rabitt** [comment]
FYI I left the two remaining TODOs from #387. @genisplaja there's one about "phrases" in Saraga, I wasn't sure what the format is, so maybe you can put some comments there?

**Comment by genisplaja** [comment]
Sure! I pushed the changes at @magdalenafuentes's PR #393.

**Comment by magdalenafuentes** [comment]
Closed via #393
