### ISSUE TITLE
Specify license for integrated datasets

### ISSUE THREAD

**Issue by genisplaja** [mir-dataset-loaders/mirdata#397]
We were discussing with Pedro and Xavier that we should include in the LICENSE file that the specified license is just for MIRDATA itself and that each dataset included has it's own license. Then maybe it would be a good idea to attach links to the web/repo where to easily/explicitly find the license of each dataset in the documentation, or even creating a `.license()` method just like we have one for citations.

**Comment by rabitt** [comment]
I agree! At some point we talked about putting that information in the dataset table in the docs. We should also put a disclaimer somewhere saying that we don't take responsibility for the accuracy of the license information and it's up to the user to verify.

**Comment by PRamoneda** [comment]
BTW @rabitt tomorrow we come back to work! focusing on the 12th release!

**Comment by magdalenafuentes** [comment]
Closing #383 since this issue overlaps

**Comment by magdalenafuentes** [comment]
@PRamoneda @genisplaja under which license is tonality_classicaldb released?

**Comment by PRamoneda** [comment]
Creative commons 4.0

**Comment by PRamoneda** [comment]
That license is used in MTG by defect

**Comment by magdalenafuentes** [comment]
Then is "Creative Commons Attribution Non Commercial Share Alike 4.0 International." right?

**Comment by PRamoneda** [comment]
yes!
