### ISSUE TITLE
List of available datasets in code?

### ISSUE THREAD

**Issue by magdalenafuentes** [mir-dataset-loaders/mirdata#401]
To initialize a dataset the user needs to know the name of the dataset loader in `mirdata`, is that easily accessible anywhere? The names are not in the [table of available datasets](https://mirdata.readthedocs.io/en/latest/source/quick_reference.html).

**Comment by genisplaja** [comment]
That's true! We could add it into the table of datasets or even create some sort of `mirdata.dataset_list()` method in the core file to print out the whole list of names to initialize the datasets.

**Comment by rabitt** [comment]
That's true! It's only in the API documentation. Definitely +1 for a `mirdata.list_datasets()` method. I'll make a PR for it!

**Comment by rabitt** [comment]
So it's actually available through `mirdata.DATASETS`, but we all forgot about it 😂  so I'm making a small helper function to make it more clear + obvious in the docs

**Comment by magdalenafuentes** [comment]
Haha great :)
