### ISSUE TITLE
Convention for missing annotations

### ISSUE THREAD

**Issue by rabitt** [mir-dataset-loaders/mirdata#405]
Some datasets have tracks with missing annotations. Right now we handle them inconsistently. For example if a beat annotation is missing for a track, some loaders return `None` and some return `BeatData(None, None)`. I'm working on a PR that will add typing to the annotations.py functions to ensure we dont use the `BeatData(None, None)` case, and updates any inconsistent loaders.

cc @drubinstein

**Comment by magdalenafuentes** [comment]
Great!
