### ISSUE TITLE
Remote index starts downloading when iterating over datasets using initialize

### ISSUE THREAD

**Issue by magdalenafuentes** [mir-dataset-loaders/mirdata#409]
I can see some use cases where the user wants to iterate over the datasets and explore them (see below). Right now, if you do that, `acousticbrainz_genre` starts downloading the `REMOTE_INDEX` and slows down things a lot. This makes me think `initialize()` is not where we want to download the index. I know there was a discussion about doing it in `download()` but that wouldn't allow for iterating on the track ids unless you do `dataset.download()` first. What about printing a message when the index is not present letting the user know they have to download it? @PRamoneda I know you where on it, thoughts? @rabitt 

```
for module in mirdata.DATASETS:
      dataset = mirdata.initialize(module, data_home=path)
      print(module)
      print(dataset.readme)
```

**Comment by rabitt** [comment]
To me, having the index download when initializing the dataset is what I'd expect mirdata to do.

@magdalenafuentes what's your use case for doing
```
for module in mirdata.DATASETS:
      dataset = mirdata.initialize(module, data_home=path)
      print(module)
      print(dataset.readme)
```

**Comment by magdalenafuentes** [comment]
Maybe there aren't many since the docs are much more complete now, but I imagined that for the generators we're planning to incorporate it might be an issue, though it would be only for the first time. I guess that it is ok like this then :). Closing the issue!
