### ISSUE TITLE
 Moving questions to discussions - new feature re-added soon

### ISSUE THREAD

**Issue by magdalenafuentes** [mir-dataset-loaders/mirdata#415]
I found [here](https://github.com/github/feedback/discussions/2952) a post that explains that there used to be a feature to easily move issues to discussions (instead of copy-pasting them and ending up with a weird format). The Github team remove it momentarily due to a bug, but it seems it will be back soon. I suggest we wait until the feature is back to move the issues with the label `question` there. Thoughts?

**Comment by rabitt** [comment]
Yes I agree!

**Comment by rabitt** [comment]
FYI I requested early re-access:
https://github.com/github/feedback/discussions/2952#discussioncomment-308890

**Comment by rabitt** [comment]
We now have early re-access, closing this!
