### ISSUE TITLE
Add `how to test` to readme

### ISSUE THREAD

**Issue by drubinstein** [mir-dataset-loaders/mirdata#44]
Maybe a subissue of #18, but we should also include an example of how to clone and install for test purposes.

Something like
For local development/integration testing:
```
Install pyenv
Create python virtual environment
Add functionality and test
```

For running the test suite:
```
Install tox
Run tox
```

**Comment by lostanlen** [comment]
The test files look very "boilerplate". The first 100 lines of `test_orchset.py` and `test_beatles.py` are almost indistinguishable. Surely this can be refactored somehow? 

What i'd like to see, as a contributor who's not a core dev of mirdata, is a plain English explanation of what minimal features a candidate `test_X.py` is supposed to test. But maybe this is explained in paper to appear at ISMIR 2019?

A readme file containing instruction on how to install pyenv and tox is all good, but i'm concerned that the part about `Add functionality and test` might lack sufficient detail for within-library consistency.

**Comment by tkell** [comment]
Hello @lostanlen, I am taking a shot at some of these things in #88!

For the boilerplate, I don't think it makes sense to remove it unless we make a base class that ever dataset class inherits from - which I recall we discussed and we don't want to do?  (cc @rabitt for confirmation of that)

**Comment by tkell** [comment]
Closing with #88, moved discussion about how to test downloaders to #91!
