### ISSUE TITLE
core.track_path(key)

### ISSUE THREAD

**Issue by rabitt** [mir-dataset-loaders/mirdata#442]
The loaders have a very similar repeated line all over the code:
`self.beats_path = os.path.join(self._data_home, self._track_paths["beats"][0])`
`self.audio_path = os.path.join(self._data_home, self._track_paths["audio"][0])`
`...`

We should generalize this to a function in core

**Comment by SK9712** [comment]
can you specify the files where this code is written?

**Comment by SK9712** [comment]
ok never mind got it. can I put that function into seperate file and use it across all the files.
