### ISSUE TITLE
Expanding NoteData and F0Data classes

### ISSUE THREAD

**Issue by genisplaja** [mir-dataset-loaders/mirdata#470]
Hello,

I am working on the implementation of the [TONAS dataset](https://zenodo.org/record/1290722). It has f0 and notes annotations, and both annotations have **energy** information. I was thinking about expanding `F0Data` and `NoteData` classes in the loader into `F0DataTonas` and `NoteDataTonas` to be able to consider the new attribute energy.
However, I can also expand the annotations themselves in `annotations.py`, and then we would leave the `energy` attribute empty for the datasets that do not have energy annotations. 

@rabitt, @magdalenafuentes, @nkundiushuti, what are your thoughts about that?

**Comment by rabitt** [comment]
@genisplaja What about using the `confidence` field, but with a note/issue to update it when we update the Annotation classes to include units (e.g. energy vs. velocity vs. confidence).

**Comment by genisplaja** [comment]
Thanks @rabitt for the comment! Last Monday's meeting we discussed a bit about that matter. We argued that expanding the annotations in the loaders can produce quite a confusing setting with several different versions of the root annotations around. For that reason, I think that we can perfectly work it out with your proposed idea and re-open this discussion when we include the units. What do you think @magdalenafuentes and @nkundiushuti? I am going to update the PR soon:) 
By the way, I sent a message to Emília Gómez to clarify the exact units for the _energy_ annotation, given that it is not specified in the dataset documentation. I'll let you know!
