### ISSUE TITLE
MD5 checksum differs

### ISSUE THREAD

**Issue by migperfer** [mir-dataset-loaders/mirdata#494]
Hello. I'm trying to use the `Queen` and `Beatles` datasets, but I'm having problems with the MD5 checksums when I call `.download()`.

The errors I'm getting for both datasets are respectively
```
/mir_datasets/beatles/annotations/The Beatles Annotations.tar.gz has an MD5 checksum (c3b7d505e033ea9ff0d7a1d57871f2ee) differing from expected (62425c552d37c6bb655a78e4603828cc), file may be corrupted.
``` 
and 
```
/mir_datasets/queen/annotations/Queen Annotations.tar.gz has an MD5 checksum (7eb9b366fa7763d6a08c32aeb823d932) differing from expected (fe11217d32bc222ae418425441974046), file may be corrupted.
```

I manually erased both `tar.gz` files and tried to download them again. However, the error still there and the MD5 of the downloaded files still the same ones across all the erase and download processes.

**Comment by genisplaja** [comment]
Hello @migperfer! I checked the case of Beatles myself and it's working fine in my machine. I am using the latest `mirdata` version in a MacBook Pro 2017 with macOS Catalina 10.15.7. The code I am running:
```
import mirdata
beatles = mirdata.initialize('beatles')
beatles.download()
# And the download works fine!
```
May I ask you about which version of the library and OS are you working with?

**Comment by genisplaja** [comment]
I just tried it in an Ubuntu 20.04.1 LTS computer and Beatles is downloading fine as well. 
Why don't you try to `pip install mirdata` and try again? Sorry for the inconvenience!

**Comment by migperfer** [comment]
We just realized that our proxy is somehow inspecting the data before sending it to our computer. However, the data still looks good after decompression. Would it be possible to add an argument like `.download(ignore_md5sum=False)`?

**Comment by rabitt** [comment]
Thanks for letting us know! Glad you found the issue @migperfer - I'll close this issue in the meantime but feel free to reopen it if something else comes up.

I like your idea to have the option to ignore checksum errors as an optional override. I'll open a new issue for this and tag you.
