### ISSUE TITLE
Option to ignore md5 checksum inconsistencies during download

### ISSUE THREAD

**Issue by rabitt** [mir-dataset-loaders/mirdata#495]
In some exceptional cases, the md5 checksum of a downloaded file may not match what we expect (e.g. see #494 ), but after decompression, the internal files have the expected checksums.

To avoid this, we could add a `allow_invalid_checksum` boolean option to `download_utils.downloader` (which defaults to `False`), which prints a warning when a checksum is invalid but does not raise an exception, and prompts the user to run validation afterward to ensure the integrity of the downloaded data.

(Thanks @migperfer for pointing out this issue and for the idea!)

**Comment by magdalenafuentes** [comment]
I like this idea! 

What if we make `cleanup` dependent on that boolean, and if we're not checking `checksums` by default when we download we delete the compressed files?

**Comment by migperfer** [comment]
I guess this one is done then? :)

**Comment by nkundiushuti** [comment]
solved in #530
