### ISSUE TITLE
Datasets with train/test/validation splits

### ISSUE THREAD

**Issue by migperfer** [mir-dataset-loaders/mirdata#516]
Hi! I was thinking about adding [Magenta's NSynth dataset](https://magenta.tensorflow.org/datasets/nsynth). The problem is that it has 3 different splits (train, test, validation), and I'm not sure about your thoughts on _mirdata_ handling this. Could it be possible to add datasets with splits to _mirdata_, or is it better to just add the three of them together?

**Comment by genisplaja** [comment]
I would suggest to add the three splits in a single loader. You can add an attribute to the class `Track` called, for instance, `split`, which is a string that can be `train`, `validation` or `test`. Thus, users will be able to filter the tracks by split by just checking what `Track.split` is.
See IRMAS loader for an example of that.

**Comment by migperfer** [comment]
Thanks for the idea and the example!

But this situation gave me an idea. Wouldn´t be nice to actually have some sort of splitting tool inside _mirdata_ to enhance reproducibility? For example, let's say that I split `dataset A`  into `train` and `test` with a fixed `seed` so other people can reproduce my results.

```
orchset = mirdata.initialize('orchset')  # get the orchset dataset
orchset.download()  # download orchset
orchset.validate()  # validate orchset
tracks_train, tracks_validation = orchset.split_dataset([0.7, 0.3], seed=0.40)  # easily reproduce train/validation splits
...
```

**Comment by rabitt** [comment]
> But this situation gave me an idea. Wouldn´t be nice to actually have some sort of splitting tool inside mirdata to enhance reproducibility? For example, let's say that I split dataset A into train and test with a fixed seed so other people can reproduce my results.

I agree it's a good idea! It could be part of the `Dataset` base clase for example.

**Comment by Laubeee** [comment]
@migperfer Did you complete the NSynth data loder? any chance to add it to the main repo?

**Comment by migperfer** [comment]
I actually did not. I made the splitting functions, but I completely forgot about the NSynth dataset unfortunately 🫠
