### ISSUE TITLE
'mirdata.core' has no attribute 'Index' Error encountered!!

### ISSUE THREAD

**Issue by prachitui** [mir-dataset-loaders/mirdata#519]
Hello, I am trying to write the module for our dataset to integrate in mirdata library. While writing the module I encounter the given error **`AttributeError: module 'mirdata.core' has no attribute 'Index'`.** 

I even tried to run it on the dataset "tinysol"

`INDEXES = {
    "default": "6.0",
    "test": "6.0",
    "6.0": core.Index(filename="tinysol_index_6.0.json"),
}

AttributeError                            Traceback (most recent call last)
<ipython-input-12-11d1c2d4fa89> in <module>
      2     "default": "6.0",
      3     "test": "6.0",
----> 4     "6.0": core.Index(filename="tinysol_index_6.0.json"),
      5 }` 

Can you tell me why do I keep getting this error. I have installed mirdata library and I am working on conda.

**Comment by prachitui** [comment]
@magdalenafuentes @rabitt @genisplaja @nkundiushuti @PRamoneda

**Comment by magdalenafuentes** [comment]
Hey @prachitui thanks for reaching out! Let me ask you a couple questions:

To make sure that mirdata is works correctly locally, could you run the following code and let me know if it's successful?

```
import mirdata

print(mirdata.list_datasets())

tinysol = mirdata.initialize('tinysol')
tinysol.download()

# get annotations and audio for a random track
example_track = tinysol.choice_track()
instrument = example_track.instrument_full
```

Where is your module located? I mean the `name_of_your_dataset.py`, e.g. `tinysol.py`
Could you share here the code in which you're trying to access the `Index`?
