### ISSUE TITLE
Dataset that I am trying to integrate in mirdata not directly downloadable.

### ISSUE THREAD

**Issue by prachitui** [mir-dataset-loaders/mirdata#522]
Hello, I am trying to integrate our dataset IDMT-SMT-BASS in the mirdata library but our dataset is not directly downloadable.  For downloading the dataset we have to go to [THIS](https://www.idmt.fraunhofer.de/en/publications/datasets.html) website and then fill out a short form. When I wrote the module I forgot about this so it just downloads a folder in mir_datasets_full folder and thus obviously its checksum differs.

Can you please guide as to how should we proceed about this? as we intend to keep our dataset as it is(semi-closed).

**Comment by prachitui** [comment]
@magdalenafuentes @rabitt @genisplaja @nkundiushuti @PRamoneda

**Comment by prachitui** [comment]
@magdalenafuentes @rabitt @genisplaja @nkundiushuti @PRamoneda

**Comment by genisplaja** [comment]
Hi @prachitui. Sorry for the late reply. For the semi-closed datasets we just proceed as follows: 
You need to include into mirdata the version that is downloaded from the link you appended. You should include a `DOWNLOAD_INFO` message to your loader that states that the dataset is private and that you need to download it from certain link and locate it into `mir_datasets/` folder in the home repository, or to the `data_home/` that the user prefers to use. Then, leave the `REMOTES` empty. Given that you won't have any element to download, your downloading tests should pass! You can take the `TONAS` loader as an example.

**Comment by prachitui** [comment]
> Hi @prachitui. Sorry for the late reply. For the semi-closed datasets we just proceed as follows:
> You need to include into mirdata the version that is downloaded from the link you appended. You should include a `DOWNLOAD_INFO` message to your loader that states that the dataset is private and that you need to download it from certain link and locate it into `mir_datasets/` folder in the home repository, or to the `data_home/` that the user prefers to use. Then, leave the `REMOTES` empty. Given that you won't have any element to download, your downloading tests should pass! You can take the `TONAS` loader as an example.

hi @genisplaja So, after following these steps I will stop getting the md5 checksum error as well right which I was getting because the dataset was not getting downloaded? 

Also, one more question, I do not have a metadata file for my dataset but in the module file I am taking different attributes for my dataset and I pull this information for these attributes by extracting everything from the .wav files only. I get the Assertion Error that there is not metadata for this dataset. Is it okay? or do I need to do something about this?

**Comment by genisplaja** [comment]
Yes! You have to run the `test_full_dataset` locally with the full dataset, and then when you create the PR, the tests you've written for the test file will be run and should pass!

Regarding the metadata issue, you can see the `mridangam_stroke` or `beatles` example. Both are datasets with no metadata. You should not include the `metadata`  field in your index.

**Comment by prachitui** [comment]
> Yes! You have to run the `test_full_dataset` locally with the full dataset, and then when you create the PR, the tests you've written for the test file will be run and should pass!
> 
> Regarding the metadata issue, you can see the `mridangam_stroke` or `beatles` example. Both are datasets with no metadata. You should not include the `metadata` field in your index.

Hi @genisplaja I will run all the tests and if any problem occurs I will ask you here. Thanks a ton for your response :)

**Comment by prachitui** [comment]
> Yes! You have to run the `test_full_dataset` locally with the full dataset, and then when you create the PR, the tests you've written for the test file will be run and should pass!
> 
> Regarding the metadata issue, you can see the `mridangam_stroke` or `beatles` example. Both are datasets with no metadata. You should not include the `metadata` field in your index.

Hi @genisplaja I tried running the 'test_full_dataset' on my code and the tonas dataset it gives almost the same error for both of them.
For tonas-
`FAILED tests / test_full_dataset.py :: test_validation - AssertionError: assert {'metadata': ... ected '], ...}} == {' metadata ': {},' tracks': {}}
FAILED tests / test_full_dataset.py::test_load_tracks - FileNotFoundError: [Errno 2] No such file or directory: 'tests / resources / mir_datasets_full / tonas / Martinetes2 / 69-M2_ElTorta.wav'`

For My dataset-
`FAILED tests / test_full_dataset.py -: test_validation 'tracks': {'... 1.wav'], ...}} == {'tracks': {}}
FAILED tests / test_full_dataset.py :: test_load_tracks - FileNotFoundError: [Errno 2] No such file or directory: 'tests / resources / mir_datasets_full / IDMT_SMT_BASS / ES / VI / BS_1_EQ_2_FS_VI_2_3.wav'
`

I have put this file inside the test/resources/mir_datasets/IDMT_SMT_BASS and I did remove REMOTE from my module. I don't know why is this error coming. Can you help please?

**Comment by prachitui** [comment]
@genisplaja

**Comment by genisplaja** [comment]
For the case of TONAS... have you actually requested the dataset and stored it in `tests/resources/mir_datasets_full`?

**Comment by prachitui** [comment]
> For the case of TONAS... have you actually requested the dataset and stored it in `tests/resources/mir_datasets_full`?

Hi @genisplaja I did not include the full dataset of  my dataset or tonas in the folder tests/resources/mir_datasets_full thats what popped the error.
Furthermore, I ran the local `pytest tests/ --local`, `pytest tests/datasets/test_mydatasetname.py` and `pytest -s tests/test_full_dataset.py --local --dataset mydatasetname` and I get the below 
`tests/test_full_dataset.py::test_download
  /home/ps/.local/lib/python3.9/site-packages/librosa/core/constantq.py:1059: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    dtype=np.complex,

-- Docs: https://docs.pytest.org/en/stable/warnings.html
================================================================================================= 4 passed, 1 skipped, 1 warning in 6.62s ===`

So, the warning is just deprecation warning. Is my dataset ready for a pull request now?
Thank you for all the help in advance :)

**Comment by genisplaja** [comment]
Yes, please do that! When you create the PR, CircleCI and codecov will automatically check that everything is properly tested and that all the tests are passing. Then we can move the discussion to the PR if some problems appear. Thank you for your contribution:)

**Comment by prachitui** [comment]
> Yes, please do that! When you create the PR, CircleCI and codecov will automatically check that everything is properly tested and that all the tests are passing. Then we can move the discussion to the PR if some problems appear. Thank you for your contribution:)

@genisplaja  Hi thank you so much. I was a little bit dubious about the **1 skipped part here**
 `= 4 passed, 1 skipped, 1 warning in 6.62s ===``  but I guess that is for the download part as our dataset is not openly downloadable. Thank you so much for helping throughout the process, really appreciate it. :)

**Comment by genisplaja** [comment]
Hi @prachitui! Are you still working on implementing the IDMT-SMT-BASS data loader?

**Comment by prachitui** [comment]
Hi Genis, no. I am done now.

**Comment by genisplaja** [comment]
Understood! Are you still planning to create a PR for this dataset then?
