### ISSUE TITLE
Loading Slakh tracks in Windows

### ISSUE THREAD

**Issue by migperfer** [mir-dataset-loaders/mirdata#542]
Loading tracks from Slakh in windows result in an exception.

In [slakh.py](https://github.com/mir-dataset-loaders/mirdata/blob/e591c5411c41591e8606812df869dca1ad52ee0f/mirdata/datasets/slakh.py#L141) there is a particular line that uses `os.sep` to use the OS separator,  but `self._track_paths["metadata"][0]` returns always the linux-like path `'slakh2100_flac_redux/train/TrackXXXXX/metadata.yaml'` so using `os.sep` fails. 

I guess importing `pathlib` and replacing that line for `self.split = str(PurePath(self._track_paths["metadata"][0])).split(os.sep)[1]` should resolve the problem, but I cannot really test it since it is impossible to clone mirdata in windows as stated in issue #517 .

**Comment by harshpalan** [comment]
Fixed with #567
