### ISSUE TITLE
Adding the latest version of compmusic_otmm_makam

### ISSUE THREAD

**Issue by sertansenturk** [mir-dataset-loaders/mirdata#551]
Hello mirdata people!

[As we discussed aeons ago](https://github.com/mir-dataset-loaders/mirdata/pull/435#issuecomment-771002659), `compmusic_otmm_makam` has a fix version that was not available when @genisplaja was implementing the original loader.

It was added to Zenodo ([link](https://zenodo.org/record/4883680#.Yt6xPexKhpQ)) later, and it would be nice to have the latest version available in `mirdata`. I believe it is a small task, and I am happy to make the change myself.

To the best of my understanding, all I need to do is to follow the guideline in [contributing.html#datasets-with-multiple-versions](https://mirdata.readthedocs.io/en/latest/source/contributing.html#datasets-with-multiple-versions):

- [ ] Add [dlfm2016-fix1](https://zenodo.org/record/4883680) to [INDEX](https://github.com/mir-dataset-loaders/mirdata/blob/master/mirdata/datasets/compmusic_otmm_makam.py#L60)
- [ ] Point `default` to the fix version

As the acceptance criteria, I could:

- Add/update the unittests
- Run (ad-hoc?) integration tests ensuring either version is downloaded appropriately.

Please let me know your thoughts, if I need to show extra care on some bits & bobs, and please do not hesitate to point out any concerns.

P.S: pinging @nkundiushuti, @genisplaja, @rabitt for visibility

**Comment by genisplaja** [comment]
Yes! We actually got started with discussions with @sertansenturk on how to push this update forward but it is still pending... I can work on that issue when I'm back from the conferences in India. I think the fix is quite easy to apply, so I'll note it down in my TODO list :)
