### ISSUE TITLE
test_egfxset.py is failing due to librosa API change

### ISSUE THREAD

**Issue by dagett** [mir-dataset-loaders/mirdata#578]
The test `tests/datasets/test_egfxset.py` is failing in checks for #576 #577. The test fails where the latest version of [librosa](https://librosa.org/doc/0.10.0/changelog.html) 0.10.0 is used - py37 and py38 but not for py36 which is not supported by librosa so uses the old release, version 0.9.2.

It seems the call inside `mirdata/annotations.py`  to `librosa.hz_to_note()` in latest librosa returns a `ndarray` instead as for 0.9.2, a `list`. The test expects a `list` so fails its assert in `tests/test_utils.py` and `run_track_tests()`.

There might be many ways to fix this, a short-term one is to lock librosa to version 0.9.2, that should should allow `test_egfxset.py` to get the expected datatype for all Python versions, and pass those tests. Another is to remove support for Python 3.6 (already EOL) and update the test.

**Comment by genisplaja** [comment]
Hey @dagett! Thank you very much for bringing this up last month. That helped a lot! We will be removing 3.6 support and moving to 3.9 (and maybe 3.10 soon) to address this problem. I am closing this issue, thanks for your contribution!
