### ISSUE TITLE
Remove support for Python 3.6, adding 3.9

### ISSUE THREAD

**Issue by guillemcortes** [mir-dataset-loaders/mirdata#580]
Hi all,

I open this issue as a reference thread for the upcoming PR I'll be doing in which I'll be addressing current mirdata issues (I have @genisplaja green light):
- Fixing black version to 23.1.0
- Bump librosa related stuff to use array (so it doesn't break python3.6 support)
- Fix tox.ini to have the three passenv variables in new lines
- Mock pandas import at docs/conf.py for sphinx autodoc

Path forward:
- Support to python3.9 and python3.10 and terminate python 3.6 support.

**Comment by guillemcortes** [comment]
python3.6 test is failing because black 23.1.0 is not available. Should we terminate python3.6 support in this release?
https://app.circleci.com/pipelines/github/mir-dataset-loaders/mirdata/2651/workflows/8ead522b-aec5-4b06-be1a-3ab8e90c42e3/jobs/9351

**Comment by genisplaja** [comment]
Maybe we could soften the black version for now? Like `black>=22.x.x`, so that in python 3.6 we install the original, and for python 3.7 and 3.8 we install the new one and the tests in circle ci should pass!

**Comment by guillemcortes** [comment]
But if python 3.6 installs black 22.x.x and python 3.7 installs 23.x.x both tests won't pass because you will have formatted the files at one specific black version so when testing with the other the test will fail. The easiest/quickest option would be to fix black version to the latest available in python3.6 and format the files with it. Python3.7 and 3.8 would also install the same version so the tests won't fail. Maybe we can do this and update the black version to >= 23.1.0 when we terminate py36 support.

**Comment by genisplaja** [comment]
oops of course, you're right. Sorry about that :) Yes probably what you suggest is the best option for now, so we can move on with the ongoing PRs, and when we remove support for 3.6 we update black to the 23 version.

**Comment by guillemcortes** [comment]
great, I'll go ahead, then :)
