### ISSUE TITLE
How to download ikala data ?

### ISSUE THREAD

**Issue by ucasiggcas** [mir-dataset-loaders/mirdata#83]
Dear,

When I go to the ikala data web [link](http://mac.citi.sinica.edu.tw/ikala/), I find that it is no longer available.
So how to get the dataset ?
Please help me,
Thx

**Comment by lostanlen** [comment]
Hello @ucasiggcas.

Unfortunately, the iKala dataset is no longer available for download. 
Please see this message:
https://github.com/mir-dataset-loaders/mirdata/blob/master/mirdata/ikala.py#L94
