### ISSUE TITLE
What to FAQ?!

### ISSUE THREAD

**Issue by keunwoochoi** [mir-dataset-loaders/mirdata#87]
Working on #18. I'd like to hear about anything we wanna add to the FAQ section.

**Comment by rabitt** [comment]
Some ideas:

* how do I add a new loader? (Link to a page we need to write!)
* how do I get access to a dataset if the download function says it’s not available?
* what do I do if my data fails validation?
* how do you choose the data that is used to create the checksums?
* why didn’t you release a version of this library in matlab/C/java/R?
* the download link is broken in a loader. What do I do?

**Comment by lostanlen** [comment]
* why the name, mirdata?

(there is no definition of the acronym MIR in the README)

**Comment by rabitt** [comment]
* If I find a mistake in an annotation, should I fix it in the loader?

**Comment by magdalenafuentes** [comment]
Related to that one:

- Found a mistake in an annotation or made a modification in a loader with respect to a previous version, where to report it?
