### ISSUE TITLE
Testing similar functionality

### ISSUE THREAD

**Issue by tkell** [mir-dataset-loaders/mirdata#91]
This was part of #44 - we have functions like `download` and `validate` that are similar but not always the same across many datasets.

Testing these functions is a pain because it requires mocking a lot of IO, and is unfriendly to new people.  On the other hand, it is nice to have tests for important functions.

In a discussion with @rabitt, we discussed:
- Not testing these functions.  👻 
- Making a base class and testing these functions there. 🏗 
- Testing these functions per-dataset. 📜 📖 ✍️ 

What do folks think?  cc @rabitt, @lostanlen, @andreasjansson

**Comment by drubinstein** [comment]
I support writing a module for "common download io" and then using that in the validate and download functions that are similar. We wont have to test in the similar functions (hopefully) as long as they dont do weird things but will keep the same level of decoupled datasets that we currently have.

**Comment by lostanlen** [comment]
naturally, i'm less concerned about an untested `download` than an untested `validate` ...

**Comment by rabitt** [comment]
Some thoughts on testing `validate`...
1) Every module's validate is nearly identical
_Yes, this could be broken out into one function in utils, but then each loader would not have its own `.validate()` command - instead users would need to call e.g. `utils.validator(index=beatles.INDEX, data_home)`. We decided it was important for it to be transparent how to validate each dataset, so we opted for the slightly redundant solution._
2) each module's validate internally calls `utils.validator()`, which does all the heavy lifting, and is already well-tested

Given that, I don't think skipping tests for each individual module's `.validate()` functions is catastrophic :)

**Comment by rabitt** [comment]
On a common downloading function - 

I would love to find a clean way to do this. The common use cases I can think of across the datasets so far are:
1) Downloading data from public links (often multiple for dataset)
2) If applicable, unzipping/untaring the downloaded data and moving it to the right place
3) Printing a message for how to download any non-public content

I guess we could have a monster common download function like:
`utils.downloader(data_home, zip_downloads=None, tar_downloads=None, file_downloads=None, info_message=None)`
Where any of the `None` arguments can be lists. Then a module's download method would be specifying the arguments like
```python
# in orchset.py
def download(data_home=None):
    if data_home is None:
        data_home = utils.get_default_dataset_path(DATA_DIR)
    utils.downloader(data_home, zip_data=REMOTE)
```
Similar to validator,  we could test the general heavy-lifting download functionality in `utils.downloader()` and ignore testing the module specific ones.

Then there's the force-overwriting issue (right now many download methods have a `force_overwrite` flag, which deletes and redownloads existing data). The more I think about it the more I don't like having the option to force overwrite at all. In particular, there are datasets where e.g. the annotations are public but the audio isn't. In this case, should a force overwrite only delete the annotations? (probably yes) but this gets messy quick. Thinking we should remove force-overwrite all together and skip downloading per file if it's already there. Thoughts on this?

**Comment by rabitt** [comment]
I opened #99 to see how it would work, and i like it a lot. I thiiiink this will solve this overall issue - we can test all the core download functionality with heavy tests in `test_utils`, and ignore all the dataset-specific instances.

**Comment by drubinstein** [comment]
Generally this is the shape I wanted. However, I'd not do a kitchen sink download function. Instead I'd name the module `web_downloader.py` and then have separate functions for tar, zip, unzip etc. that could be tested separately.

A slightly (more fancy) solution is to have a `downloader` function in `web_downloader.py` that takes another function as an argument. For example, 
`web_downloader.downloader(web_downloader.tar_downloader, data_home)` would use the tar_downloader and also do the `data_home` check and logging. In this case `tar_downloader` is a function in the form of 
`def tar_downloader(data_home)`

You probably can move the data_home check into the web downloader too if you wanted.

**Comment by rabitt** [comment]
@drubinstein great idea. I'll adapt #99 to break out everything into it's own module.

**Comment by rabitt** [comment]
Closing this, I think we've found a good solution!
